import { useCallback } from "react";
import { Plus } from "lucide-react";
import { cn } from "@/lib/utils";
import type { DiffLine as DiffLineType } from "@/lib/diff-parser";

interface DiffLineProps {
  line: DiffLineType;
  filePath?: string;
  highlightedContent?: string;
  /** When set, a + icon appears on hover to add a comment */
  onAddComment?: () => void;
  hasComments?: boolean;
}

const lineTypeStyles: Record<DiffLineType["type"], string> = {
  add: "bg-green-50/60 dark:bg-green-950/20",
  remove: "bg-red-50/60 dark:bg-red-950/20",
  context: "",
};

const lineNumberStyles: Record<DiffLineType["type"], string> = {
  add: "bg-green-100/40 dark:bg-green-950/30",
  remove: "bg-red-100/40 dark:bg-red-950/30",
  context: "",
};

const linePrefix: Record<DiffLineType["type"], string> = {
  add: "+",
  remove: "-",
  context: " ",
};

export function DiffLineRow({ line, filePath, highlightedContent, onAddComment, hasComments }: DiffLineProps) {
  const handleLineNumberClick = useCallback(
    (lineNum: number | null, side: "L" | "R") => {
      if (lineNum == null) return;
      const anchor = filePath
        ? `${filePath.replace(/[^a-zA-Z0-9._/-]/g, "")}-${side}${lineNum}`
        : `${side}${lineNum}`;
      window.history.replaceState(null, "", `#${anchor}`);
    },
    [filePath]
  );

  return (
    <div
      id={
        filePath && line.newLineNumber != null
          ? `${filePath.replace(/[^a-zA-Z0-9._/-]/g, "")}-L${line.newLineNumber}`
          : undefined
      }
      className={cn("flex text-[13px] font-mono leading-[20px] group relative", lineTypeStyles[line.type])}
    >
      {/* Comment add button — shown on hover */}
      {onAddComment && (
        <button
          onClick={onAddComment}
          className={cn(
            "absolute left-0 top-0 h-[20px] w-[20px] flex items-center justify-center z-10",
            "text-primary bg-primary/10 rounded-sm",
            hasComments
              ? "opacity-60 hover:opacity-100"
              : "opacity-0 group-hover:opacity-100",
            "transition-opacity"
          )}
          title="Add comment"
        >
          <Plus className="h-3 w-3" />
        </button>
      )}
      {/* Old line number gutter */}
      <button
        type="button"
        onClick={() => handleLineNumberClick(line.oldLineNumber, "L")}
        className={cn(
          "w-[50px] shrink-0 text-right pr-2 select-none text-[11px] text-muted-foreground/60 hover:text-primary cursor-pointer",
          lineNumberStyles[line.type]
        )}
      >
        {line.oldLineNumber ?? ""}
      </button>
      {/* New line number gutter */}
      <button
        type="button"
        onClick={() => handleLineNumberClick(line.newLineNumber, "R")}
        className={cn(
          "w-[50px] shrink-0 text-right pr-2 select-none text-[11px] text-muted-foreground/60 hover:text-primary cursor-pointer",
          lineNumberStyles[line.type]
        )}
      >
        {line.newLineNumber ?? ""}
      </button>
      {/* Prefix (+/-/space) */}
      <div className="w-[20px] shrink-0 text-center select-none text-muted-foreground/50">
        {linePrefix[line.type]}
      </div>
      {/* Content */}
      <div className="flex-1 min-w-0 pr-4 whitespace-pre">
        {highlightedContent ? (
          // Safe: HTML generated by Shiki's codeToTokens — only produces <span style="color:..."> from grammar engine, not from user input
          <span dangerouslySetInnerHTML={{ __html: highlightedContent }} />
        ) : (
          <span>{line.content || "\u00A0"}</span>
        )}
      </div>
    </div>
  );
}
