package cluster

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/assembledhq/143/internal/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/pashagolub/pgxmock/v4"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/require"
)

type mockPlanStore struct {
	plan models.PMPlan
	err  error
}

func (m *mockPlanStore) GetLatestByOrg(ctx context.Context, orgID uuid.UUID) (models.PMPlan, error) {
	return m.plan, m.err
}

type mockSchedulerLock struct{}

func (m *mockSchedulerLock) TryAcquire(ctx context.Context) (bool, error) { return true, nil }
func (m *mockSchedulerLock) Release(ctx context.Context) error            { return nil }

type mockJobs struct {
	failedJob *models.LatestJobError
}

func (m *mockJobs) Enqueue(ctx context.Context, orgID uuid.UUID, queue, jobType string, payload any, priority int, dedupeKey *string) (uuid.UUID, error) {
	return uuid.New(), nil
}

func (m *mockJobs) GetLatestFailedByType(ctx context.Context, orgID uuid.UUID, jobType string) (*models.LatestJobError, error) {
	return m.failedJob, nil
}

type mockOrgs struct {
	org models.Organization
}

func (m *mockOrgs) GetByID(ctx context.Context, id uuid.UUID) (models.Organization, error) {
	return m.org, nil
}

type mockIntegrations struct {
	orgs []uuid.UUID
}

func (m *mockIntegrations) ListOrgsWithActiveIntegrations(ctx context.Context) ([]uuid.UUID, error) {
	return m.orgs, nil
}

type mockRepos struct {
	repos []models.Repository
}

func (m *mockRepos) ListByOrg(ctx context.Context, orgID uuid.UUID) ([]models.Repository, error) {
	return m.repos, nil
}

type mockProjects struct {
	projects    []models.Project
	listErr     error
	updatedIDs  []uuid.UUID
	updatedNext []time.Time
}

func (m *mockProjects) ListDueForSchedule(ctx context.Context, now time.Time) ([]models.Project, error) {
	return m.projects, m.listErr
}

func (m *mockProjects) UpdateNextRunAt(ctx context.Context, orgID, projectID uuid.UUID, nextRunAt time.Time) error {
	m.updatedIDs = append(m.updatedIDs, projectID)
	m.updatedNext = append(m.updatedNext, nextRunAt)
	return nil
}

type trackingJobs struct {
	enqueued []string // jobType values
}

func (m *trackingJobs) Enqueue(ctx context.Context, orgID uuid.UUID, queue, jobType string, payload any, priority int, dedupeKey *string) (uuid.UUID, error) {
	m.enqueued = append(m.enqueued, jobType)
	return uuid.New(), nil
}

func (m *trackingJobs) GetLatestFailedByType(ctx context.Context, orgID uuid.UUID, jobType string) (*models.LatestJobError, error) {
	return nil, nil
}

type mockPMDocs struct {
	docs map[uuid.UUID]models.PMDocument
	errs map[uuid.UUID]error
}

func (m *mockPMDocs) GetByOrgAndSourceType(ctx context.Context, orgID uuid.UUID, sourceType string) (models.PMDocument, error) {
	if err, ok := m.errs[orgID]; ok {
		return models.PMDocument{}, err
	}
	if doc, ok := m.docs[orgID]; ok {
		return doc, nil
	}
	return models.PMDocument{}, pgx.ErrNoRows
}

func TestScheduler_SetPMDocStore(t *testing.T) {
	t.Parallel()

	s := &Scheduler{logger: zerolog.Nop()}
	require.Nil(t, s.pmDocs, "pmDocs should be nil before SetPMDocStore")

	ps := &mockPMDocs{}
	s.SetPMDocStore(ps)
	require.NotNil(t, s.pmDocs, "pmDocs should be set after SetPMDocStore")
}

func TestScheduler_ScheduleContextRefreshes_NilStore(t *testing.T) {
	t.Parallel()

	jobs := &trackingJobs{}
	s := &Scheduler{
		jobs:   jobs,
		logger: zerolog.Nop(),
	}

	// Should not panic when pmDocs is nil.
	s.scheduleContextRefreshes(context.Background(), []uuid.UUID{uuid.New()}, map[uuid.UUID]models.OrgSettings{}, time.Now())
	require.Empty(t, jobs.enqueued, "should not enqueue any jobs when pmDocs is nil")
}

func TestScheduler_ScheduleContextRefreshes_NoDoc(t *testing.T) {
	t.Parallel()

	orgID := uuid.New()
	jobs := &trackingJobs{}
	s := &Scheduler{
		jobs:   jobs,
		pmDocs: &mockPMDocs{},
		logger: zerolog.Nop(),
	}

	orgSettings := map[uuid.UUID]models.OrgSettings{
		orgID: {ContextRefreshIntervalDays: models.DefaultContextRefreshIntervalDays},
	}

	s.scheduleContextRefreshes(context.Background(), []uuid.UUID{orgID}, orgSettings, time.Now())
	require.Empty(t, jobs.enqueued, "should not enqueue jobs when no autogenerated doc exists")
}

func TestScheduler_ScheduleContextRefreshes_FreshDoc(t *testing.T) {
	t.Parallel()

	orgID := uuid.New()
	now := time.Now()
	syncedAt := now.Add(-3 * 24 * time.Hour) // 3 days ago

	jobs := &trackingJobs{}
	s := &Scheduler{
		jobs: jobs,
		pmDocs: &mockPMDocs{
			docs: map[uuid.UUID]models.PMDocument{
				orgID: {LastSyncedAt: &syncedAt},
			},
		},
		logger: zerolog.Nop(),
	}

	orgSettings := map[uuid.UUID]models.OrgSettings{
		orgID: {ContextRefreshIntervalDays: models.DefaultContextRefreshIntervalDays},
	}

	s.scheduleContextRefreshes(context.Background(), []uuid.UUID{orgID}, orgSettings, now)
	require.Empty(t, jobs.enqueued, "should not enqueue refresh for fresh doc")
}

func TestScheduler_ScheduleContextRefreshes_StaleDoc(t *testing.T) {
	t.Parallel()

	orgID := uuid.New()
	now := time.Now()
	syncedAt := now.Add(-15 * 24 * time.Hour) // 15 days ago, past 14-day default

	jobs := &trackingJobs{}
	s := &Scheduler{
		jobs: jobs,
		pmDocs: &mockPMDocs{
			docs: map[uuid.UUID]models.PMDocument{
				orgID: {LastSyncedAt: &syncedAt},
			},
		},
		logger: zerolog.Nop(),
	}

	orgSettings := map[uuid.UUID]models.OrgSettings{
		orgID: {ContextRefreshIntervalDays: models.DefaultContextRefreshIntervalDays},
	}

	s.scheduleContextRefreshes(context.Background(), []uuid.UUID{orgID}, orgSettings, now)
	require.Len(t, jobs.enqueued, 1, "should enqueue one refresh job")
	require.Equal(t, models.JobTypePMContextRefresh, jobs.enqueued[0])
}

func TestScheduler_ScheduleContextRefreshes_NilLastSyncedAt(t *testing.T) {
	t.Parallel()

	orgID := uuid.New()
	jobs := &trackingJobs{}
	s := &Scheduler{
		jobs: jobs,
		pmDocs: &mockPMDocs{
			docs: map[uuid.UUID]models.PMDocument{
				orgID: {LastSyncedAt: nil},
			},
		},
		logger: zerolog.Nop(),
	}

	orgSettings := map[uuid.UUID]models.OrgSettings{
		orgID: {ContextRefreshIntervalDays: models.DefaultContextRefreshIntervalDays},
	}

	s.scheduleContextRefreshes(context.Background(), []uuid.UUID{orgID}, orgSettings, time.Now())
	require.Empty(t, jobs.enqueued, "should not enqueue refresh when LastSyncedAt is nil")
}

func TestNewScheduler(t *testing.T) {
	t.Parallel()

	s := NewScheduler(
		&mockSchedulerLock{},
		&mockJobs{},
		&mockOrgs{},
		&mockIntegrations{},
		&mockPlanStore{},
		&mockRepos{},
		zerolog.Nop(),
	)
	require.NotNil(t, s, "NewScheduler should return a non-nil scheduler")
	require.Nil(t, s.projects, "projects should be nil by default")
}

func TestScheduler_SetProjectStore(t *testing.T) {
	t.Parallel()

	s := &Scheduler{logger: zerolog.Nop()}
	require.Nil(t, s.projects, "projects should be nil before SetProjectStore")

	ps := &mockProjects{}
	s.SetProjectStore(ps)
	require.NotNil(t, s.projects, "projects should be set after SetProjectStore")
}

func TestScheduler_ScheduleProjectCycles_ListError(t *testing.T) {
	t.Parallel()

	projects := &mockProjects{listErr: pgx.ErrNoRows}
	jobs := &trackingJobs{}

	s := &Scheduler{
		jobs:     jobs,
		projects: projects,
		logger:   zerolog.Nop(),
	}

	// Should not panic, should log error and continue.
	s.scheduleProjectCycles(context.Background(), time.Now())
	require.Empty(t, jobs.enqueued, "should not enqueue any jobs on list error")
}

func TestScheduler_ScheduleProjectCycles_NilStore(t *testing.T) {
	t.Parallel()

	s := &Scheduler{
		logger: zerolog.Nop(),
	}
	// Should not panic when projects store is nil.
	s.scheduleProjectCycles(context.Background(), time.Now())
}

func TestScheduler_ScheduleProjectCycles_EnqueuesAndAdvances(t *testing.T) {
	t.Parallel()

	orgID := uuid.New()
	projID := uuid.New()
	now := time.Now()

	projects := &mockProjects{
		projects: []models.Project{
			{
				ID:               projID,
				OrgID:            orgID,
				ScheduleEnabled:  true,
				ScheduleInterval: 2,
				ScheduleUnit:     "days",
			},
		},
	}
	jobs := &trackingJobs{}

	s := &Scheduler{
		lock:         &mockSchedulerLock{},
		jobs:         jobs,
		orgs:         &mockOrgs{},
		integrations: &mockIntegrations{},
		plans:        &mockPlanStore{err: pgx.ErrNoRows},
		repos:        &mockRepos{},
		projects:     projects,
		logger:       zerolog.Nop(),
	}

	s.scheduleProjectCycles(context.Background(), now)

	require.Len(t, jobs.enqueued, 1, "should enqueue one job")
	require.Equal(t, "project_cycle", jobs.enqueued[0])
	require.Len(t, projects.updatedIDs, 1, "should advance next_run_at for one project")
	require.Equal(t, projID, projects.updatedIDs[0])
	// next_run_at should be 2 days from now.
	expected := now.AddDate(0, 0, 2)
	require.Equal(t, expected, projects.updatedNext[0])
}

func TestScheduler_ScheduleProjectCycles_NoDueProjects(t *testing.T) {
	t.Parallel()

	projects := &mockProjects{projects: nil}
	jobs := &trackingJobs{}

	s := &Scheduler{
		jobs:     jobs,
		projects: projects,
		logger:   zerolog.Nop(),
	}

	s.scheduleProjectCycles(context.Background(), time.Now())

	require.Empty(t, jobs.enqueued, "should not enqueue any jobs")
	require.Empty(t, projects.updatedIDs, "should not update any projects")
}

func TestScheduler_ShouldRunPM_NoPlans(t *testing.T) {
	t.Parallel()

	s := &Scheduler{
		lock:         &mockSchedulerLock{},
		jobs:         &mockJobs{},
		orgs:         &mockOrgs{},
		integrations: &mockIntegrations{},
		plans:        &mockPlanStore{err: pgx.ErrNoRows},
		repos:        &mockRepos{},
		logger:       zerolog.Nop(),
	}

	run, err := s.shouldRunPM(context.Background(), uuid.New(), time.Now(), 4*time.Hour)
	require.NoError(t, err, "shouldRunPM should not error")
	require.True(t, run, "should run when no plans exist")
}

func TestScheduler_ShouldRunPM_TooSoon(t *testing.T) {
	t.Parallel()

	now := time.Now()
	s := &Scheduler{
		lock:         &mockSchedulerLock{},
		jobs:         &mockJobs{},
		orgs:         &mockOrgs{},
		integrations: &mockIntegrations{},
		plans:        &mockPlanStore{plan: models.PMPlan{CreatedAt: now}},
		repos:        &mockRepos{},
		logger:       zerolog.Nop(),
	}

	run, err := s.shouldRunPM(context.Background(), uuid.New(), now, 4*time.Hour)
	require.NoError(t, err, "shouldRunPM should not error")
	require.False(t, run, "should not run before schedule interval")
}

func TestScheduler_ShouldRunPM_Overdue(t *testing.T) {
	t.Parallel()

	now := time.Now()
	s := &Scheduler{
		lock:         &mockSchedulerLock{},
		jobs:         &mockJobs{},
		orgs:         &mockOrgs{},
		integrations: &mockIntegrations{},
		plans:        &mockPlanStore{plan: models.PMPlan{CreatedAt: now.Add(-5 * time.Hour)}},
		repos:        &mockRepos{},
		logger:       zerolog.Nop(),
	}

	run, err := s.shouldRunPM(context.Background(), uuid.New(), now, 4*time.Hour)
	require.NoError(t, err, "shouldRunPM should not error")
	require.True(t, run, "should run when schedule interval elapsed")
}

func TestScheduler_ShouldRunPM_RecentFailure(t *testing.T) {
	t.Parallel()

	now := time.Now()
	failedAt := now.Add(-30 * time.Minute) // failed 30 min ago, within 4h failure backoff
	s := &Scheduler{
		lock: &mockSchedulerLock{},
		jobs: &mockJobs{failedJob: &models.LatestJobError{
			JobID:     uuid.New(),
			LastError: "sandbox error",
			UpdatedAt: failedAt,
		}},
		orgs:         &mockOrgs{},
		integrations: &mockIntegrations{},
		plans:        &mockPlanStore{err: pgx.ErrNoRows}, // no successful plan
		repos:        &mockRepos{},
		logger:       zerolog.Nop(),
	}

	run, err := s.shouldRunPM(context.Background(), uuid.New(), now, 4*time.Hour)
	require.NoError(t, err, "shouldRunPM should not error")
	require.False(t, run, "should not run when a recent failure exists within the failure backoff")
}

func TestScheduler_ShouldRunPM_OldFailure(t *testing.T) {
	t.Parallel()

	now := time.Now()
	failedAt := now.Add(-5 * time.Hour) // failed 5 hours ago, beyond 4h failure backoff
	s := &Scheduler{
		lock: &mockSchedulerLock{},
		jobs: &mockJobs{failedJob: &models.LatestJobError{
			JobID:     uuid.New(),
			LastError: "sandbox error",
			UpdatedAt: failedAt,
		}},
		orgs:         &mockOrgs{},
		integrations: &mockIntegrations{},
		plans:        &mockPlanStore{err: pgx.ErrNoRows}, // no successful plan
		repos:        &mockRepos{},
		logger:       zerolog.Nop(),
	}

	run, err := s.shouldRunPM(context.Background(), uuid.New(), now, 4*time.Hour)
	require.NoError(t, err, "shouldRunPM should not error")
	require.True(t, run, "should run when the failure is older than the failure backoff")
}

// --- automation scheduling ---

type mockAutomations struct {
	due           []models.Automation
	listErr       error
	inFlight      map[uuid.UUID]int
	inFlightErr   error
	advanceErr    error
	advancedIDs   []uuid.UUID
	advancedNexts []time.Time
}

func (m *mockAutomations) ListDueForSchedule(ctx context.Context, tx pgx.Tx, now time.Time) ([]models.Automation, error) {
	return m.due, m.listErr
}

func (m *mockAutomations) AdvanceNextRunAt(ctx context.Context, tx pgx.Tx, automationID uuid.UUID, now time.Time, nextRunAt time.Time) error {
	m.advancedIDs = append(m.advancedIDs, automationID)
	m.advancedNexts = append(m.advancedNexts, nextRunAt)
	return m.advanceErr
}

func (m *mockAutomations) CountInFlightRuns(ctx context.Context, tx pgx.Tx, automationID uuid.UUID) (int, error) {
	if m.inFlightErr != nil {
		return 0, m.inFlightErr
	}
	return m.inFlight[automationID], nil
}

type mockAutomationRuns struct {
	created      []models.AutomationRun
	createFlag   bool // value returned by CreateRunInTx
	createErr    error
	reapCount    int64
	reapErr      error
	reapCalls    int
	lastThresh   time.Duration
}

func (m *mockAutomationRuns) CreateRunInTx(ctx context.Context, tx pgx.Tx, r *models.AutomationRun) (bool, error) {
	if m.createErr != nil {
		return false, m.createErr
	}
	if m.createFlag {
		r.ID = uuid.New()
	}
	m.created = append(m.created, *r)
	return m.createFlag, nil
}

func (m *mockAutomationRuns) ReapStuckRuns(ctx context.Context, threshold time.Duration) (int64, error) {
	m.reapCalls++
	m.lastThresh = threshold
	return m.reapCount, m.reapErr
}

// newAutomationFixture builds an interval-scheduled automation with sensible
// defaults for scheduler tests.
func newAutomationFixture() models.Automation {
	orgID := uuid.New()
	autoID := uuid.New()
	interval := 1
	unit := "days"
	nextRun := time.Now().Add(-time.Minute)
	return models.Automation{
		ID:            autoID,
		OrgID:         orgID,
		Name:          "test",
		Goal:          "goal",
		ExecutionMode: "sequential",
		MaxConcurrent: 1,
		BaseBranch:    "main",
		ScheduleType:  models.AutomationScheduleInterval,
		IntervalValue: &interval,
		IntervalUnit:  &unit,
		Timezone:      "UTC",
		NextRunAt:     &nextRun,
		Enabled:       true,
	}
}

func TestScheduler_ScheduleAutomationRuns_NilStores(t *testing.T) {
	t.Parallel()

	s := &Scheduler{logger: zerolog.Nop()}
	// Must not panic when automation stores are not wired.
	s.scheduleAutomationRuns(context.Background(), time.Now())
}

func TestScheduler_ScheduleAutomationRuns_HappyPath(t *testing.T) {
	t.Parallel()

	mockPool, err := pgxmock.NewPool()
	require.NoError(t, err)
	defer mockPool.Close()

	mockPool.ExpectBegin()
	mockPool.ExpectCommit()

	a := newAutomationFixture()
	automations := &mockAutomations{due: []models.Automation{a}}
	runs := &mockAutomationRuns{createFlag: true}
	jobs := &trackingJobs{}

	s := &Scheduler{
		jobs:           jobs,
		automations:    automations,
		automationRuns: runs,
		pool:           mockPool,
		logger:         zerolog.Nop(),
	}

	s.scheduleAutomationRuns(context.Background(), time.Now())

	require.NoError(t, mockPool.ExpectationsWereMet(), "all pgxmock expectations should be met")
	require.Len(t, runs.created, 1, "should create one run")
	require.Equal(t, models.AutomationTriggeredBySchedule, runs.created[0].TriggeredBy)
	require.Len(t, automations.advancedIDs, 1, "should advance next_run_at once")
	require.Equal(t, a.ID, automations.advancedIDs[0])
	require.Len(t, jobs.enqueued, 1, "should enqueue the job after commit")
	require.Equal(t, models.JobTypeAutomationRun, jobs.enqueued[0])
}

func TestScheduler_ScheduleAutomationRuns_MaxConcurrentSaturated(t *testing.T) {
	t.Parallel()

	mockPool, err := pgxmock.NewPool()
	require.NoError(t, err)
	defer mockPool.Close()

	mockPool.ExpectBegin()
	mockPool.ExpectCommit()

	a := newAutomationFixture()
	a.MaxConcurrent = 1
	automations := &mockAutomations{
		due:      []models.Automation{a},
		inFlight: map[uuid.UUID]int{a.ID: 1}, // saturated
	}
	runs := &mockAutomationRuns{}
	jobs := &trackingJobs{}

	s := &Scheduler{
		jobs:           jobs,
		automations:    automations,
		automationRuns: runs,
		pool:           mockPool,
		logger:         zerolog.Nop(),
	}

	s.scheduleAutomationRuns(context.Background(), time.Now())

	require.NoError(t, mockPool.ExpectationsWereMet())
	require.Empty(t, runs.created, "saturated automation must not create a run row")
	require.Empty(t, jobs.enqueued, "saturated automation must not enqueue a job")
	require.Len(t, automations.advancedIDs, 1, "next_run_at should still advance so we don't busy-loop")
}

func TestScheduler_ScheduleAutomationRuns_DuplicateIdempotencySkip(t *testing.T) {
	t.Parallel()

	mockPool, err := pgxmock.NewPool()
	require.NoError(t, err)
	defer mockPool.Close()

	mockPool.ExpectBegin()
	mockPool.ExpectCommit()

	a := newAutomationFixture()
	automations := &mockAutomations{due: []models.Automation{a}}
	runs := &mockAutomationRuns{createFlag: false} // idempotency hit → no insert
	jobs := &trackingJobs{}

	s := &Scheduler{
		jobs:           jobs,
		automations:    automations,
		automationRuns: runs,
		pool:           mockPool,
		logger:         zerolog.Nop(),
	}

	s.scheduleAutomationRuns(context.Background(), time.Now())

	require.NoError(t, mockPool.ExpectationsWereMet())
	// On duplicate we do NOT advance next_run_at — whoever inserted the row
	// already owns the advance, and re-advancing risks overwriting their value.
	require.Empty(t, automations.advancedIDs, "duplicate skip must not advance next_run_at")
	require.Empty(t, jobs.enqueued, "duplicate runs must not enqueue a job")
}

func TestScheduler_ScheduleAutomationRuns_AdvanceErrorAbortsTick(t *testing.T) {
	t.Parallel()

	// A DB error inside the loop leaves pgx's tx aborted, so subsequent
	// queries silently no-op. The fix: on Advance failure we return without
	// commit so the tx rolls back and the next tick retries cleanly.
	mockPool, err := pgxmock.NewPool()
	require.NoError(t, err)
	defer mockPool.Close()

	mockPool.ExpectBegin()
	mockPool.ExpectRollback() // from deferred tx.Rollback; no Commit expected

	a := newAutomationFixture()
	b := newAutomationFixture() // a second automation that must NOT be enqueued
	automations := &mockAutomations{
		due:        []models.Automation{a, b},
		advanceErr: errors.New("advance boom"),
	}
	runs := &mockAutomationRuns{createFlag: true}
	jobs := &trackingJobs{}

	s := &Scheduler{
		jobs:           jobs,
		automations:    automations,
		automationRuns: runs,
		pool:           mockPool,
		logger:         zerolog.Nop(),
	}

	s.scheduleAutomationRuns(context.Background(), time.Now())

	require.NoError(t, mockPool.ExpectationsWereMet(), "tx should roll back, not commit")
	require.Empty(t, jobs.enqueued, "no jobs must be enqueued when the tick aborts")
}

func TestScheduler_ReapStuckAutomationRuns_CalledFromRunOnce(t *testing.T) {
	t.Parallel()

	runs := &mockAutomationRuns{reapCount: 3}
	s := &Scheduler{
		automationRuns: runs,
		logger:         zerolog.Nop(),
	}

	s.reapStuckAutomationRuns(context.Background())

	require.Equal(t, 1, runs.reapCalls, "reaper should run exactly once")
	require.Equal(t, stuckAutomationRunThreshold, runs.lastThresh, "reaper should pass the tuned threshold")
}

func TestScheduler_ReapStuckAutomationRuns_NilStoreNoop(t *testing.T) {
	t.Parallel()

	s := &Scheduler{logger: zerolog.Nop()}
	// Must not panic when automationRuns is not wired.
	s.reapStuckAutomationRuns(context.Background())
}

func TestScheduler_ReapStuckAutomationRuns_StoreError(t *testing.T) {
	t.Parallel()

	runs := &mockAutomationRuns{reapErr: pgx.ErrTxClosed}
	s := &Scheduler{
		automationRuns: runs,
		logger:         zerolog.Nop(),
	}

	// Must swallow errors — a failed reap should not crash the scheduler tick.
	s.reapStuckAutomationRuns(context.Background())
	require.Equal(t, 1, runs.reapCalls)
}
