package models

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type CodeReviewScope string

const (
	CodeReviewScopeFull         CodeReviewScope = "full"
	CodeReviewScopeEvidenceOnly CodeReviewScope = "evidence_only"
)

func (s CodeReviewScope) Validate() error {
	if s == CodeReviewScopeFull || s == CodeReviewScopeEvidenceOnly {
		return nil
	}
	return fmt.Errorf("invalid code review scope %q", s)
}

type CodeReviewAssessmentRouteReason string

const (
	CodeReviewRouteInitialFull       CodeReviewAssessmentRouteReason = "initial_full"
	CodeReviewRouteVisualChanged     CodeReviewAssessmentRouteReason = "visual_changed"
	CodeReviewRouteCodeChanged       CodeReviewAssessmentRouteReason = "code_changed"
	CodeReviewRouteContractChanged   CodeReviewAssessmentRouteReason = "contract_changed"
	CodeReviewRouteIntentChanged     CodeReviewAssessmentRouteReason = "intent_changed"
	CodeReviewRouteRequestChanged    CodeReviewAssessmentRouteReason = "request_changed"
	CodeReviewRouteGatesChanged      CodeReviewAssessmentRouteReason = "gates_changed"
	CodeReviewRouteNoBaseline        CodeReviewAssessmentRouteReason = "no_complete_baseline"
	CodeReviewRouteBaselineBlocked   CodeReviewAssessmentRouteReason = "baseline_not_visual_only"
	CodeReviewRouteEvidenceInvalid   CodeReviewAssessmentRouteReason = "evidence_validation_failed"
	CodeReviewRouteInputsUnavailable CodeReviewAssessmentRouteReason = "inputs_unavailable"
	CodeReviewRouteForceFresh        CodeReviewAssessmentRouteReason = "force_fresh"
	CodeReviewRouteDispute           CodeReviewAssessmentRouteReason = "dispute"
)

func (r CodeReviewAssessmentRouteReason) Validate() error {
	switch r {
	case CodeReviewRouteInitialFull, CodeReviewRouteVisualChanged, CodeReviewRouteCodeChanged, CodeReviewRouteContractChanged, CodeReviewRouteIntentChanged, CodeReviewRouteRequestChanged, CodeReviewRouteGatesChanged, CodeReviewRouteNoBaseline, CodeReviewRouteBaselineBlocked, CodeReviewRouteEvidenceInvalid, CodeReviewRouteInputsUnavailable, CodeReviewRouteForceFresh, CodeReviewRouteDispute:
		return nil
	}
	return fmt.Errorf("invalid code review assessment route reason %q", r)
}

type CodeReviewAssessmentStatus string

const (
	CodeReviewAssessmentReserved   CodeReviewAssessmentStatus = "reserved"
	CodeReviewAssessmentRunning    CodeReviewAssessmentStatus = "running"
	CodeReviewAssessmentPublishing CodeReviewAssessmentStatus = "publishing"
	CodeReviewAssessmentCompleted  CodeReviewAssessmentStatus = "completed"
	CodeReviewAssessmentSuperseded CodeReviewAssessmentStatus = "superseded"
	CodeReviewAssessmentFailed     CodeReviewAssessmentStatus = "failed"
	CodeReviewAssessmentCancelled  CodeReviewAssessmentStatus = "cancelled"
)

func (s CodeReviewAssessmentStatus) Validate() error {
	switch s {
	case CodeReviewAssessmentReserved, CodeReviewAssessmentRunning, CodeReviewAssessmentPublishing, CodeReviewAssessmentCompleted, CodeReviewAssessmentSuperseded, CodeReviewAssessmentFailed, CodeReviewAssessmentCancelled:
		return nil
	}
	return fmt.Errorf("invalid code review assessment status %q", s)
}

type CodeReviewResultOrigin string

const (
	CodeReviewResultExecuted     CodeReviewResultOrigin = "executed"
	CodeReviewResultReused       CodeReviewResultOrigin = "reused"
	CodeReviewResultEvidenceOnly CodeReviewResultOrigin = "evidence_only"
)

func (s CodeReviewResultOrigin) Validate() error {
	if s == CodeReviewResultExecuted || s == CodeReviewResultReused || s == CodeReviewResultEvidenceOnly {
		return nil
	}
	return fmt.Errorf("invalid code review result origin %q", s)
}

type CodeReviewPublicationState string

const (
	CodeReviewPublicationNotStarted  CodeReviewPublicationState = "not_started"
	CodeReviewPublicationReserved    CodeReviewPublicationState = "reserved"
	CodeReviewPublicationUncertain   CodeReviewPublicationState = "uncertain"
	CodeReviewPublicationConfirmed   CodeReviewPublicationState = "confirmed"
	CodeReviewPublicationNotRequired CodeReviewPublicationState = "not_required"
)

func (s CodeReviewPublicationState) Validate() error {
	switch s {
	case CodeReviewPublicationNotStarted, CodeReviewPublicationReserved, CodeReviewPublicationUncertain, CodeReviewPublicationConfirmed, CodeReviewPublicationNotRequired:
		return nil
	}
	return fmt.Errorf("invalid code review publication state %q", s)
}

// CodeReviewAssessmentCapture is immutable once inserted. ID can be allocated before
// visual evidence is captured; a nil ID is generated by the store.
type CodeReviewAssessmentCapture struct {
	ID                            uuid.UUID
	OrgID                         uuid.UUID
	RepositoryID                  uuid.UUID
	PullRequestID                 uuid.UUID
	PolicyID                      uuid.UUID
	SessionID                     uuid.UUID
	Generation                    int64
	ConversationID                *uuid.UUID
	SourceAssessmentID            *uuid.UUID
	PreviousAssessmentID          *uuid.UUID
	PreviousPublishedAssessmentID *uuid.UUID
	BaseSHA                       string
	BaseRef                       string
	HeadSHA                       string
	InputVersion                  int
	CodeDigest                    string
	ContractDigest                string
	IntentDigest                  string
	VisualDigest                  string
	RequestDigest                 string
	GateDigest                    string
	InputDigest                   string
	InputManifest                 json.RawMessage
	ReviewScope                   CodeReviewScope
	RouteReason                   CodeReviewAssessmentRouteReason
	PublicationKey                string
}

type CodeReviewAssessment struct {
	ID                            uuid.UUID                       `db:"id" json:"id"`
	OrgID                         uuid.UUID                       `db:"org_id" json:"-"`
	RepositoryID                  uuid.UUID                       `db:"repository_id" json:"repository_id"`
	RepositoryFullName            string                          `db:"repository_full_name" json:"repository_full_name"`
	PullRequestID                 uuid.UUID                       `db:"pull_request_id" json:"pull_request_id"`
	MetadataID                    uuid.UUID                       `db:"metadata_id" json:"-"`
	PolicyID                      uuid.UUID                       `db:"policy_id" json:"policy_id"`
	SessionID                     uuid.UUID                       `db:"session_id" json:"session_id"`
	Generation                    int64                           `db:"generation" json:"generation"`
	ConversationID                *uuid.UUID                      `db:"conversation_id" json:"conversation_id,omitempty"`
	SourceAssessmentID            *uuid.UUID                      `db:"source_assessment_id" json:"source_assessment_id,omitempty"`
	PreviousAssessmentID          *uuid.UUID                      `db:"previous_assessment_id" json:"previous_assessment_id,omitempty"`
	PreviousPublishedAssessmentID *uuid.UUID                      `db:"previous_published_assessment_id" json:"previous_published_assessment_id,omitempty"`
	SupersededByAssessmentID      *uuid.UUID                      `db:"superseded_by_assessment_id" json:"superseded_by_assessment_id,omitempty"`
	BaseSHA                       string                          `db:"base_sha" json:"base_sha"`
	BaseRef                       string                          `db:"base_ref" json:"base_ref"`
	HeadSHA                       string                          `db:"head_sha" json:"head_sha"`
	InputVersion                  int                             `db:"input_version" json:"input_version"`
	CodeDigest                    string                          `db:"code_digest" json:"code_digest"`
	ContractDigest                string                          `db:"contract_digest" json:"contract_digest"`
	IntentDigest                  string                          `db:"intent_digest" json:"intent_digest"`
	VisualDigest                  string                          `db:"visual_digest" json:"visual_digest"`
	RequestDigest                 string                          `db:"request_digest" json:"request_digest"`
	GateDigest                    string                          `db:"gate_digest" json:"gate_digest"`
	InputDigest                   string                          `db:"input_digest" json:"input_digest"`
	InputManifest                 json.RawMessage                 `db:"input_manifest" json:"input_manifest"`
	ReviewScope                   CodeReviewScope                 `db:"review_scope" json:"review_scope"`
	RouteReason                   CodeReviewAssessmentRouteReason `db:"route_reason" json:"route_reason"`
	ResultOrigin                  *CodeReviewResultOrigin         `db:"result_origin" json:"result_origin,omitempty"`
	CoverageComplete              bool                            `db:"coverage_complete" json:"coverage_complete"`
	Status                        CodeReviewAssessmentStatus      `db:"status" json:"status"`
	Decision                      *CodeReviewDecision             `db:"decision" json:"decision,omitempty"`
	Acceptable                    *bool                           `db:"acceptable" json:"acceptable,omitempty"`
	RiskReasonDetails             json.RawMessage                 `db:"risk_reason_details" json:"risk_reason_details,omitempty"`
	StructuredOutcome             json.RawMessage                 `db:"structured_outcome" json:"structured_outcome,omitempty"`
	RenderedBody                  *string                         `db:"rendered_body" json:"rendered_body,omitempty"`
	FailureDetail                 *string                         `db:"failure_detail" json:"failure_detail,omitempty"`
	PublicationKey                string                          `db:"publication_key" json:"publication_key"`
	PublicationState              CodeReviewPublicationState      `db:"publication_state" json:"publication_state"`
	PublicationReceipt            json.RawMessage                 `db:"publication_receipt" json:"publication_receipt,omitempty"`
	GitHubReviewID                *int64                          `db:"github_review_id" json:"github_review_id,omitempty"`
	GitHubReviewURL               *string                         `db:"github_review_url" json:"github_review_url,omitempty"`
	SubmittedCommitSHA            *string                         `db:"submitted_commit_sha" json:"submitted_commit_sha,omitempty"`
	CreatedAt                     time.Time                       `db:"created_at" json:"created_at"`
	CompletedAt                   *time.Time                      `db:"completed_at" json:"completed_at,omitempty"`
	SupersededAt                  *time.Time                      `db:"superseded_at" json:"superseded_at,omitempty"`
}

type CodeReviewAssessmentCompletion struct {
	ResultOrigin      CodeReviewResultOrigin
	CoverageComplete  bool
	Decision          CodeReviewDecision
	Acceptable        bool
	RiskReasonDetails json.RawMessage
	StructuredOutcome json.RawMessage
	RenderedBody      string
}

// CodeReviewAssessmentSummary is the bounded current/active/latest-failure PR projection.
// Full input manifests and evidence remain available from the detail reader.
type CodeReviewAssessmentSummary struct {
	ID                 uuid.UUID                       `json:"id"`
	PullRequestID      uuid.UUID                       `json:"-"`
	SessionID          uuid.UUID                       `json:"session_id"`
	SourceAssessmentID *uuid.UUID                      `json:"source_assessment_id,omitempty"`
	Status             CodeReviewAssessmentStatus      `json:"status"`
	ReviewScope        CodeReviewScope                 `json:"review_scope"`
	RouteReason        CodeReviewAssessmentRouteReason `json:"route_reason"`
	Decision           *CodeReviewDecision             `json:"decision,omitempty"`
	Acceptable         *bool                           `json:"acceptable,omitempty"`
	RiskReasonDetails  json.RawMessage                 `json:"risk_reason_details,omitempty"`
	HeadSHA            string                          `json:"head_sha"`
	PublicationState   CodeReviewPublicationState      `json:"publication_state"`
	CreatedAt          time.Time                       `json:"created_at"`
	CompletedAt        *time.Time                      `json:"completed_at,omitempty"`
}
