DROP TRIGGER IF EXISTS trg_pull_requests_sync_changeset_state_update ON pull_requests;
DROP TRIGGER IF EXISTS trg_pull_requests_sync_changeset_state_insert ON pull_requests;
DROP FUNCTION IF EXISTS sync_pull_request_changeset_state();
DROP TRIGGER IF EXISTS trg_pull_requests_assign_primary_changeset ON pull_requests;
DROP FUNCTION IF EXISTS assign_pull_request_primary_changeset();
DROP TRIGGER IF EXISTS trg_primary_changeset_mirror_session_publish_state ON session_changesets;
DROP FUNCTION IF EXISTS mirror_primary_changeset_publish_state_to_session();
DROP TRIGGER IF EXISTS trg_session_publish_state_mirror_primary_changeset_update ON session_publish_state;
DROP TRIGGER IF EXISTS trg_session_publish_state_mirror_primary_changeset_insert ON session_publish_state;
DROP FUNCTION IF EXISTS mirror_session_publish_state_to_primary_changeset();
DROP TRIGGER IF EXISTS trg_primary_changeset_mirror_session_branches ON session_changesets;
DROP FUNCTION IF EXISTS mirror_primary_changeset_branches_to_session();
DROP TRIGGER IF EXISTS trg_sessions_mirror_primary_changeset_branches ON sessions;
DROP FUNCTION IF EXISTS mirror_session_branches_to_primary_changeset();
DROP TRIGGER IF EXISTS trg_sessions_create_primary_changeset ON sessions;
DROP FUNCTION IF EXISTS create_primary_session_changeset();
DROP TRIGGER IF EXISTS trg_session_changesets_require_primary_update ON session_changesets;
DROP TRIGGER IF EXISTS trg_session_changesets_require_primary_delete ON session_changesets;
DROP FUNCTION IF EXISTS enforce_session_primary_changeset();
ALTER TABLE pull_requests DROP COLUMN IF EXISTS changeset_id;
DROP TABLE IF EXISTS session_changesets;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_id_org_id_key;
