DROP TRIGGER IF EXISTS preview_links_enqueue_live_invalidation ON preview_links;
DROP TRIGGER IF EXISTS preview_targets_enqueue_live_invalidation ON preview_targets;
DROP TRIGGER IF EXISTS session_preview_prewarm_runs_enqueue_live_invalidation ON session_preview_prewarm_runs;
DROP TRIGGER IF EXISTS automation_goal_improvements_enqueue_live_invalidation ON automation_goal_improvements;
DROP TRIGGER IF EXISTS eval_runs_enqueue_live_invalidation ON eval_runs;
DROP FUNCTION IF EXISTS enqueue_live_related_invalidation();
DROP TRIGGER IF EXISTS code_review_metadata_enqueue_live_invalidation ON code_review_session_metadata;
DROP TRIGGER IF EXISTS eval_bootstrap_runs_enqueue_live_invalidation ON eval_bootstrap_runs;
DROP TRIGGER IF EXISTS eval_batches_enqueue_live_invalidation ON eval_batches;
DROP TRIGGER IF EXISTS pull_requests_enqueue_live_invalidation ON pull_requests;
DROP FUNCTION IF EXISTS enqueue_live_invalidation();
DROP TRIGGER IF EXISTS organization_memberships_enqueue_live_authorization_change ON organization_memberships;
DROP FUNCTION IF EXISTS enqueue_live_authorization_change();
DROP TRIGGER IF EXISTS session_publish_state_touch_live_projection ON session_publish_state;
DROP FUNCTION IF EXISTS touch_session_live_projection_from_publish_state();
DROP TRIGGER IF EXISTS automation_runs_enqueue_live_projection ON automation_runs;
DROP TRIGGER IF EXISTS automations_enqueue_live_projection ON automations;
DROP TRIGGER IF EXISTS preview_instances_enqueue_live_projection ON preview_instances;
DROP TRIGGER IF EXISTS sessions_enqueue_live_projection ON sessions;
DROP FUNCTION IF EXISTS enqueue_live_projection();
DROP TRIGGER IF EXISTS automation_runs_bump_live_version ON automation_runs;
DROP TRIGGER IF EXISTS automations_bump_live_version ON automations;
DROP TRIGGER IF EXISTS preview_instances_bump_live_version ON preview_instances;
DROP TRIGGER IF EXISTS sessions_bump_live_version ON sessions;
DROP FUNCTION IF EXISTS bump_live_version();
DROP TRIGGER IF EXISTS live_event_outbox_notify ON live_event_outbox;
DROP FUNCTION IF EXISTS notify_live_event_outbox();
DROP TABLE IF EXISTS live_event_outbox;
DROP FUNCTION IF EXISTS validate_live_event_json(jsonb);
ALTER TABLE automation_runs DROP COLUMN IF EXISTS live_version;
ALTER TABLE automations DROP COLUMN IF EXISTS live_version;
ALTER TABLE preview_instances DROP COLUMN IF EXISTS live_version;
ALTER TABLE sessions DROP COLUMN IF EXISTS live_version;
