ALTER TABLE code_review_session_metadata
    ADD COLUMN files_changed integer,
    ADD COLUMN additions integer,
    ADD COLUMN deletions integer,
    ADD COLUMN lines_changed integer,
    ADD COLUMN risk_reason_details jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD CONSTRAINT chk_code_review_session_metadata_files_changed
        CHECK (files_changed IS NULL OR files_changed >= 0),
    ADD CONSTRAINT chk_code_review_session_metadata_additions
        CHECK (additions IS NULL OR additions >= 0),
    ADD CONSTRAINT chk_code_review_session_metadata_deletions
        CHECK (deletions IS NULL OR deletions >= 0),
    ADD CONSTRAINT chk_code_review_session_metadata_lines_changed
        CHECK (lines_changed IS NULL OR lines_changed >= 0),
    ADD CONSTRAINT chk_code_review_session_metadata_change_breakdown
        CHECK (
            (additions IS NULL AND deletions IS NULL)
            OR (
                additions IS NOT NULL
                AND deletions IS NOT NULL
                AND lines_changed IS NOT NULL
                AND lines_changed = additions + deletions
            )
        );

-- Recent review bodies include change statistics in one of two paragraphs
-- generated by BuildCodeReviewFinalReviewBody. Only recover values from those
-- stable paragraphs: summaries and findings are model-authored text and can
-- independently mention a different number of changed lines. Parse as numeric
-- first so an unexpectedly large value cannot abort this migration when it is
-- narrowed to the integer columns below.
--
-- Reviews that predate the generated fact remain NULL and are reported
-- separately from the size sample. The body does not preserve additions and
-- deletions independently, so those breakdowns begin with newly completed
-- reviews rather than inventing a historical split.
WITH matched AS MATERIALIZED (
    SELECT
        id,
        regexp_match(
            final_review_body,
            E'(?:^|\\n)[*][*](?:Review facts:[*][*] |Why:[*][*] It met the configured policy: )([0-9]{1,20}) changed lines? across ([0-9]{1,20}) files?(?: ·| and |,|[.]|\\n|$)'
        ) AS change_stats
    FROM code_review_session_metadata
    WHERE final_review_body IS NOT NULL
),
extracted AS (
    SELECT
        id,
        change_stats[1]::numeric AS lines_changed,
        change_stats[2]::numeric AS files_changed
    FROM matched
    WHERE change_stats IS NOT NULL
),
bounded AS (
    SELECT
        id,
        lines_changed::integer AS lines_changed,
        files_changed::integer AS files_changed
    FROM extracted
    WHERE lines_changed BETWEEN 0 AND 2147483647
      AND files_changed BETWEEN 0 AND 2147483647
)
UPDATE code_review_session_metadata AS metadata
SET
    lines_changed = bounded.lines_changed,
    files_changed = bounded.files_changed
FROM bounded
WHERE metadata.id = bounded.id;

CREATE INDEX idx_code_review_metadata_analytics
    ON code_review_session_metadata (org_id, created_at DESC)
    WHERE status = 'completed';
