-- No-op rollback.
--
-- Migration 000207 records reviewed hot-table FK exceptions. Re-adding these
-- parent FKs in an automatic rollback would reintroduce the parent-row lock
-- fan-in risk and can require full validation on the partitioned session_logs
-- table. If a production rollback must restore DB-backed FKs, do it as an
-- explicit follow-up migration with a maintenance window and orphan cleanup.
