-- Seed data for preview dogfooding.
-- Creates a default organization and four users so the preview is
-- immediately usable without requiring the registration flow, plus a
-- placeholder integration and a couple of repositories/projects so the
-- logged-in UI shows populated screens instead of empty states.
--
-- IMPORTANT: seeded preview users are passwordless demo identities. Demo
-- environments enter directly through POST /api/v1/auth/demo using
-- DEMO_ENTRY_EMAIL, so no shared demo password is stored or displayed.
--
-- All rows use fixed UUIDs and conflict handlers so the seed is safely
-- re-runnable. Tables with secondary unique indexes (e.g.
-- repositories.idx_repositories_org_github) use the unqualified
-- ON CONFLICT DO NOTHING form so any unique violation — not just on id —
-- no-ops rather than aborting the transaction; identity rows use DO UPDATE
-- so old dogfood rows converge to the current preview identity data.
