-- Seed data for preview dogfooding.
-- Creates a default organization and four users so the preview is
-- immediately usable without requiring the registration flow, plus a
-- placeholder integration and a couple of repositories/projects so the
-- logged-in UI shows populated screens instead of empty states.
--
-- IMPORTANT: the seeded admin email + password below must match the
-- DEMO_EMAIL / DEMO_PASSWORD defaults in internal/config/config.go, since
-- the login-page banner renders those values and a reviewer copy-pastes
-- them into the sign-in form. If you change either side, regenerate the
-- bcrypt hash below (cost 10) and update the config defaults in lockstep.
--
-- Password for all preview users: "preview" (bcrypt hash below).
--
-- All rows use fixed UUIDs and conflict handlers so the seed is safely
-- re-runnable. Tables with secondary unique indexes (e.g.
-- repositories.idx_repositories_org_github) use the unqualified
-- ON CONFLICT DO NOTHING form so any unique violation — not just on id —
-- no-ops rather than aborting the transaction; identity rows use DO UPDATE
-- so old dogfood credentials converge to the current preview credentials.
