package domains

// IsPublicEmailDomain reports whether a (normalized, lowercase) domain is a
// public/free/disposable email provider that no organization may claim.
// Every product with domain capture enforces this denylist — letting an org
// "verify" gmail.com would auto-join the entire public internet.
//
// The list covers the major global and regional consumer providers plus the
// provider-controlled relay domains (Apple private relay, GitHub noreply).
// It is intentionally a curated set, not an exhaustive disposable-email
// list: a domain missing here still requires passing DNS verification,
// which a throwaway-provider's customers cannot do.
func IsPublicEmailDomain(domain string) bool {
	return publicEmailDomains[domain]
}

var publicEmailDomains = map[string]bool{
	// Major global providers
	"gmail.com":      true,
	"googlemail.com": true,
	"yahoo.com":      true,
	"ymail.com":      true,
	"rocketmail.com": true,
	"outlook.com":    true,
	"hotmail.com":    true,
	"live.com":       true,
	"msn.com":        true,
	"aol.com":        true,
	"icloud.com":     true,
	"me.com":         true,
	"mac.com":        true,
	"proton.me":      true,
	"protonmail.com": true,
	"protonmail.ch":  true,
	"pm.me":          true,
	"tutanota.com":   true,
	"tutamail.com":   true,
	"tuta.io":        true,
	"zoho.com":       true,
	"zohomail.com":   true,
	"fastmail.com":   true,
	"fastmail.fm":    true,
	"hey.com":        true,
	"mail.com":       true,
	"email.com":      true,
	"usa.com":        true,
	"gmx.com":        true,
	"gmx.net":        true,
	"gmx.de":         true,
	"gmx.at":         true,
	"gmx.ch":         true,
	"inbox.com":      true,
	"hushmail.com":   true,
	"mailfence.com":  true,
	"posteo.de":      true,
	"posteo.net":     true,
	"runbox.com":     true,
	"disroot.org":    true,
	"skiff.com":      true,
	"duck.com":       true,
	"mailbox.org":    true,

	// Regional Yahoo / Microsoft / AOL variants
	"yahoo.co.uk":    true,
	"yahoo.co.in":    true,
	"yahoo.co.jp":    true,
	"yahoo.fr":       true,
	"yahoo.de":       true,
	"yahoo.es":       true,
	"yahoo.it":       true,
	"yahoo.ca":       true,
	"yahoo.com.au":   true,
	"yahoo.com.br":   true,
	"yahoo.com.mx":   true,
	"hotmail.co.uk":  true,
	"hotmail.fr":     true,
	"hotmail.de":     true,
	"hotmail.es":     true,
	"hotmail.it":     true,
	"live.co.uk":     true,
	"live.fr":        true,
	"live.de":        true,
	"live.nl":        true,
	"outlook.de":     true,
	"outlook.fr":     true,
	"outlook.es":     true,
	"outlook.jp":     true,
	"outlook.com.au": true,
	"aol.co.uk":      true,

	// Regional consumer providers
	"web.de":          true,
	"t-online.de":     true,
	"freenet.de":      true,
	"orange.fr":       true,
	"wanadoo.fr":      true,
	"free.fr":         true,
	"laposte.net":     true,
	"sfr.fr":          true,
	"libero.it":       true,
	"virgilio.it":     true,
	"alice.it":        true,
	"tiscali.it":      true,
	"telefonica.es":   true,
	"terra.com":       true,
	"uol.com.br":      true,
	"bol.com.br":      true,
	"btinternet.com":  true,
	"sky.com":         true,
	"talktalk.net":    true,
	"shaw.ca":         true,
	"rogers.com":      true,
	"sympatico.ca":    true,
	"bell.net":        true,
	"telus.net":       true,
	"comcast.net":     true,
	"verizon.net":     true,
	"att.net":         true,
	"sbcglobal.net":   true,
	"cox.net":         true,
	"charter.net":     true,
	"earthlink.net":   true,
	"optonline.net":   true,
	"bellsouth.net":   true,
	"xfinity.com":     true,
	"mail.ru":         true,
	"bk.ru":           true,
	"inbox.ru":        true,
	"list.ru":         true,
	"yandex.ru":       true,
	"yandex.com":      true,
	"ya.ru":           true,
	"rambler.ru":      true,
	"qq.com":          true,
	"163.com":         true,
	"126.com":         true,
	"yeah.net":        true,
	"foxmail.com":     true,
	"sina.com":        true,
	"sina.cn":         true,
	"sohu.com":        true,
	"aliyun.com":      true,
	"naver.com":       true,
	"daum.net":        true,
	"hanmail.net":     true,
	"kakao.com":       true,
	"nate.com":        true,
	"rediffmail.com":  true,
	"seznam.cz":       true,
	"wp.pl":           true,
	"o2.pl":           true,
	"onet.pl":         true,
	"interia.pl":      true,
	"abv.bg":          true,
	"ukr.net":         true,
	"i.ua":            true,
	"bigpond.com":     true,
	"optusnet.com.au": true,
	"xtra.co.nz":      true,

	// Provider-controlled relay/alias domains: addresses here are real and
	// verified, but the *zone* belongs to the provider — an org can never
	// pass DNS verification for them, and matching on them would be
	// meaningless anyway. Listed for a clearer add-time error message.
	"privaterelay.appleid.com": true,
	"users.noreply.github.com": true,
	"anonaddy.me":              true,
	"simplelogin.com":          true,
	"mozmail.com":              true,

	// Common disposable providers
	"mailinator.com":    true,
	"guerrillamail.com": true,
	"10minutemail.com":  true,
	"temp-mail.org":     true,
	"tempmail.com":      true,
	"throwawaymail.com": true,
	"yopmail.com":       true,
	"getnada.com":       true,
	"trashmail.com":     true,
	"sharklasers.com":   true,
	"maildrop.cc":       true,
	"dispostable.com":   true,
	"fakeinbox.com":     true,
	"mintemail.com":     true,
	"mytemp.email":      true,
	"burnermail.io":     true,
}
