package pm

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/require"

	"github.com/assembledhq/143/internal/db"
	"github.com/assembledhq/143/internal/models"
	"github.com/assembledhq/143/internal/services/agent"
)

// --- mock pmDocumentStore ---

type mockPMDocStore struct {
	docs       []models.PMDocument
	created    []*models.PMDocument
	updated    []*models.PMDocument
	deleted    []uuid.UUID
	getByOrgST map[string]models.PMDocument // keyed by sourceType
	getByID    map[uuid.UUID]models.PMDocument
	createErr  error
	updateErr  error
}

func (m *mockPMDocStore) ListByOrg(_ context.Context, _ uuid.UUID) ([]models.PMDocument, error) {
	return m.docs, nil
}

func (m *mockPMDocStore) ListByOrgExcludeSourceType(_ context.Context, _ uuid.UUID, exclude string, limit int) ([]models.PMDocument, error) {
	var result []models.PMDocument
	for _, d := range m.docs {
		if d.SourceType != exclude {
			result = append(result, d)
		}
		if len(result) >= limit {
			break
		}
	}
	return result, nil
}

func (m *mockPMDocStore) GetByOrgAndSourceType(_ context.Context, _ uuid.UUID, sourceType string) (models.PMDocument, error) {
	if doc, ok := m.getByOrgST[sourceType]; ok {
		return doc, nil
	}
	return models.PMDocument{}, pgx.ErrNoRows
}

func (m *mockPMDocStore) ListByOrgAndSourceType(_ context.Context, _ uuid.UUID, sourceType string) ([]models.PMDocument, error) {
	var result []models.PMDocument
	for _, d := range m.docs {
		if d.SourceType == sourceType {
			result = append(result, d)
		}
	}
	return result, nil
}

func (m *mockPMDocStore) Create(_ context.Context, doc *models.PMDocument) error {
	if doc.ID == uuid.Nil {
		doc.ID = uuid.New()
	}
	m.created = append(m.created, doc)
	return m.createErr
}

func (m *mockPMDocStore) Update(_ context.Context, doc *models.PMDocument) error {
	m.updated = append(m.updated, doc)
	return m.updateErr
}

func (m *mockPMDocStore) Delete(_ context.Context, _ uuid.UUID, docID uuid.UUID) error {
	m.deleted = append(m.deleted, docID)
	return nil
}

func (m *mockPMDocStore) DeleteByOrgAndSourceType(_ context.Context, _ uuid.UUID, sourceType string) error {
	return nil
}

func (m *mockPMDocStore) GetByID(_ context.Context, _ uuid.UUID, docID uuid.UUID) (models.PMDocument, error) {
	if doc, ok := m.getByID[docID]; ok {
		return doc, nil
	}
	return models.PMDocument{}, pgx.ErrNoRows
}

func (m *mockPMDocStore) Begin(_ context.Context) (pgx.Tx, error) {
	return mockTx{}, nil
}

func (m *mockPMDocStore) WithTx(_ pgx.Tx) *db.PMDocumentStore {
	// Return a PMDocumentStore wrapping a no-op DBTX. In unit tests the
	// returned store isn't exercised — callers interact with mockPMDocStore
	// directly. If a test needs transactional behaviour, use pgxmock instead.
	return db.NewPMDocumentStore(nil)
}

// mockTx is a minimal pgx.Tx implementation for unit tests.
type mockTx struct{ pgx.Tx }

func (mockTx) Commit(_ context.Context) error   { return nil }
func (mockTx) Rollback(_ context.Context) error { return nil }

// --- mock credential store ---

type mockCredStore struct {
	creds map[models.ProviderName]*models.DecryptedCredential
}

// withDefaultStatus applies Status="active" when the test fixture didn't set
// one. The legacy fallback resolver in agent.AgentEnv now filters by status,
// and these PM tests pre-date that filter — every fixture would otherwise
// need to repeat `Status: "active"` for behavior that's already production
// reality.
func (m *mockCredStore) withDefaultStatus(cred *models.DecryptedCredential) *models.DecryptedCredential {
	if cred == nil || cred.Status != "" {
		return cred
	}
	copy := *cred
	copy.Status = models.CredentialStatusActive
	return &copy
}

func (m *mockCredStore) Get(_ context.Context, _ uuid.UUID, provider models.ProviderName) (*models.DecryptedCredential, error) {
	if c, ok := m.creds[provider]; ok {
		return m.withDefaultStatus(c), nil
	}
	return nil, pgx.ErrNoRows
}

func (m *mockCredStore) ListByProvider(_ context.Context, _ uuid.UUID, provider models.ProviderName) ([]models.DecryptedCredential, error) {
	if c, ok := m.creds[provider]; ok {
		return []models.DecryptedCredential{*m.withDefaultStatus(c)}, nil
	}
	return nil, pgx.ErrNoRows
}

// --- Tests ---
// Note: mockOrgStore is defined in service_test.go (same package).

func TestUpsertAutogeneratedDoc_Creates(t *testing.T) {
	t.Parallel()

	store := &mockPMDocStore{
		getByOrgST: map[string]models.PMDocument{}, // empty — no existing doc
	}
	svc := &Service{
		pmDocuments: store,
		logger:      zerolog.Nop(),
	}

	err := svc.upsertAutogeneratedDoc(context.Background(), uuid.New(), "# New Context")
	require.NoError(t, err)
	require.Len(t, store.created, 1, "should create one doc")
	require.Equal(t, "# New Context", store.created[0].Content)
	require.Equal(t, models.PMDocSourceAutogenerated, store.created[0].SourceType)
	require.Equal(t, -1, store.created[0].SortOrder)
	require.NotNil(t, store.created[0].LastSyncedAt)
}

func TestUpsertAutogeneratedDoc_Updates(t *testing.T) {
	t.Parallel()

	existingID := uuid.New()
	store := &mockPMDocStore{
		getByOrgST: map[string]models.PMDocument{
			models.PMDocSourceAutogenerated: {
				ID:      existingID,
				Content: "old content",
			},
		},
	}
	svc := &Service{
		pmDocuments: store,
		logger:      zerolog.Nop(),
	}

	err := svc.upsertAutogeneratedDoc(context.Background(), uuid.New(), "# Updated Content")
	require.NoError(t, err)
	require.Empty(t, store.created, "should not create")
	require.Len(t, store.updated, 1, "should update existing doc")
	require.Equal(t, "# Updated Content", store.updated[0].Content)
	require.NotNil(t, store.updated[0].LastSyncedAt)
}

func TestBuildBootstrapSeed_WithProductContext(t *testing.T) {
	t.Parallel()

	orgID := uuid.New()
	settings := models.OrgSettings{
		ProductContext: &models.ProductContext{
			Direction: "AI-first",
		},
	}
	settingsJSON, _ := json.Marshal(settings)

	svc := &Service{
		orgs: &mockOrgStore{
			org: models.Organization{
				ID:       orgID,
				Settings: settingsJSON,
			},
		},
		pmDocuments: &mockPMDocStore{
			docs: []models.PMDocument{
				{Title: "Roadmap", DocType: "roadmap", SourceType: models.PMDocSourceNotion},
			},
		},
		logger: zerolog.Nop(),
	}

	repo := &models.Repository{FullName: "org/repo"}
	creds := &integrationCredentials{github: true, sentry: nil}

	seedJSON, err := svc.buildBootstrapSeed(context.Background(), orgID, repo, creds)
	require.NoError(t, err)

	var seed map[string]any
	require.NoError(t, json.Unmarshal(seedJSON, &seed))
	require.Contains(t, seed, "product_context")
	require.Contains(t, seed, "connected_integrations")
	require.Contains(t, seed, "existing_pm_documents")

	integrations := seed["connected_integrations"].([]any)
	require.Contains(t, integrations, "github")
}

func TestBuildBootstrapSeed_ExcludesRefreshDocs(t *testing.T) {
	t.Parallel()

	orgID := uuid.New()
	settings := models.OrgSettings{}
	settingsJSON, _ := json.Marshal(settings)

	svc := &Service{
		orgs: &mockOrgStore{
			org: models.Organization{ID: orgID, Settings: settingsJSON},
		},
		pmDocuments: &mockPMDocStore{
			docs: []models.PMDocument{
				{Title: "Roadmap", DocType: "roadmap", SourceType: models.PMDocSourceNotion},
				{Title: "Pending Refresh", DocType: "context", SourceType: models.PMDocSourceRefresh},
			},
		},
		logger: zerolog.Nop(),
	}

	repo := &models.Repository{}
	creds := &integrationCredentials{}

	seedJSON, err := svc.buildBootstrapSeed(context.Background(), orgID, repo, creds)
	require.NoError(t, err)

	var seed map[string]any
	require.NoError(t, json.Unmarshal(seedJSON, &seed))

	docs := seed["existing_pm_documents"].([]any)
	require.Len(t, docs, 1, "should exclude refresh docs")
}

func TestFetchIntegrationCredentials_NilStore(t *testing.T) {
	t.Parallel()

	svc := &Service{credentials: nil, logger: zerolog.Nop()}
	creds := svc.fetchIntegrationCredentials(context.Background(), uuid.New())
	require.False(t, creds.github)
	require.Nil(t, creds.sentry)
	require.Nil(t, creds.linear)
	require.Nil(t, creds.notion)
}

func TestFetchIntegrationCredentials_WithCredentials(t *testing.T) {
	t.Parallel()

	svc := &Service{
		credentials: &mockCredStore{
			creds: map[models.ProviderName]*models.DecryptedCredential{
				models.ProviderSentry: {Config: models.SentryConfig{AccessToken: "sentry-tok"}},
				models.ProviderLinear: {Config: models.LinearConfig{AccessToken: "linear-tok"}},
			},
		},
		logger: zerolog.Nop(),
	}

	creds := svc.fetchIntegrationCredentials(context.Background(), uuid.New())
	require.NotNil(t, creds.sentry)
	require.NotNil(t, creds.linear)
	require.Nil(t, creds.notion, "notion not configured")
}

func TestConnectedProviderNames(t *testing.T) {
	t.Parallel()

	creds := &integrationCredentials{
		github: true,
		sentry: &models.DecryptedCredential{},
		linear: nil,
		notion: &models.DecryptedCredential{},
	}

	names := creds.connectedProviderNames()
	require.Contains(t, names, "github")
	require.Contains(t, names, string(models.ProviderSentry))
	require.Contains(t, names, string(models.ProviderNotion))
	require.NotContains(t, names, string(models.ProviderLinear))
}

func TestConnectedProviderNames_Empty(t *testing.T) {
	t.Parallel()

	creds := &integrationCredentials{}
	names := creds.connectedProviderNames()
	require.Empty(t, names)
}

func TestApplyGitHubEnv(t *testing.T) {
	t.Parallel()

	repo := &models.Repository{FullName: "octocat/hello-world"}
	env := map[string]string{}
	applyGitHubEnv(env, "gh-tok", repo)

	require.Equal(t, "gh-tok", env["GITHUB_TOKEN"])
	require.Equal(t, "octocat", env["GITHUB_REPO_OWNER"])
	require.Equal(t, "hello-world", env["GITHUB_REPO_NAME"])
}

func TestApplyGitHubEnv_EmptyInputs(t *testing.T) {
	t.Parallel()

	env := map[string]string{}
	applyGitHubEnv(env, "", nil)
	require.Empty(t, env, "empty ghToken and nil repo should leave env untouched")
}

func TestBootstrapSandboxConfig(t *testing.T) {
	t.Parallel()

	cfg := bootstrapSandboxConfig()
	require.Equal(t, 30*time.Minute, cfg.Timeout)
	require.Equal(t, "restricted", cfg.NetworkPolicy)
	// CPULimit and MemoryLimitMB inherit from DefaultSandboxConfig so a
	// single SANDBOX_* env-var change tunes both regular sessions and PM
	// bootstraps. Pin to the same defaults DefaultSandboxConfig promises.
	defaults := agent.DefaultSandboxConfig()
	require.Equal(t, defaults.CPULimit, cfg.CPULimit)
	require.Equal(t, defaults.MemoryLimitMB, cfg.MemoryLimitMB)
}
