package pm

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/assembledhq/143/internal/models"
	"github.com/assembledhq/143/internal/prompts"
	"github.com/assembledhq/143/internal/services/agent"
)

const refreshSuggestionsPath = "/workspace/.pm-context/SUGGESTIONS.md"

// RunRefresh reads the existing autogenerated context doc, runs a refresh agent
// to update it, and stores the result as a pending refresh for operator review.
func (s *Service) RunRefresh(ctx context.Context, orgID uuid.UUID) error {
	if s.sandbox == nil || s.env == nil {
		return fmt.Errorf("pm sandbox or env helper not configured")
	}
	if s.pmDocuments == nil {
		return fmt.Errorf("pm document store not configured")
	}

	existingDoc, err := s.pmDocuments.GetByOrgAndSourceType(ctx, orgID, models.PMDocSourceAutogenerated)
	if err != nil {
		return fmt.Errorf("no autogenerated context doc found — run bootstrap first: %w", err)
	}

	skillsDoc := s.buildSkillsDoc(ctx, orgID)

	creds := s.fetchIntegrationCredentials(ctx, orgID)

	lastSynced := "2 weeks ago"
	if existingDoc.LastSyncedAt != nil {
		lastSynced = existingDoc.LastSyncedAt.Format(time.RFC3339)
	}

	prompt := &agent.AgentPrompt{
		SystemPrompt: prompts.PMRefreshPrompt(prompts.PMRefreshPromptData{
			SkillsDoc:    skillsDoc,
			HasNotion:    creds.notion != nil,
			HasLinear:    creds.linear != nil,
			HasSentry:    creds.sentry != nil,
			HasGitHub:    creds.github,
			LastSyncedAt: lastSynced,
		}),
		MaxTokens: 80_000,
	}

	sb, cleanup, err := s.runAgentInSandbox(ctx, sandboxRunParams{
		orgID:   orgID,
		prompt:  prompt,
		logName: "refresh-agent",
		preExec: func(ctx context.Context, sb *agent.Sandbox) error {
			// Inject existing context doc into the sandbox so the agent can update it.
			return s.sandbox.WriteFile(ctx, sb, bootstrapOutputPath, []byte(existingDoc.Content))
		},
	})
	if err != nil {
		return err
	}
	defer cleanup()

	// Extract both files from the container.
	updatedContent, err := s.sandbox.ReadFile(ctx, sb, bootstrapOutputPath)
	if err != nil {
		return fmt.Errorf("read updated CONTEXT.md: %w", err)
	}
	suggestions, _ := s.sandbox.ReadFile(ctx, sb, refreshSuggestionsPath)

	// Delete any existing pending refresh docs and create the new one in a
	// single transaction so a crash can't lose the refresh output.
	tx, err := s.pmDocuments.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin refresh transaction: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	txStore := s.pmDocuments.WithTx(tx)

	if err := txStore.DeleteByOrgAndSourceType(ctx, orgID, models.PMDocSourceRefresh); err != nil {
		s.logger.Warn().Err(err).Str("org_id", orgID.String()).Msg("failed to delete old pending refresh docs")
	}

	now := time.Now()
	meta, _ := json.Marshal(map[string]string{
		"suggestions":     string(suggestions),
		"previous_doc_id": existingDoc.ID.String(),
	})
	pendingDoc := &models.PMDocument{
		OrgID:        orgID,
		Title:        fmt.Sprintf("PM Context Refresh — %s", now.Format("2006-01-02")),
		Content:      string(updatedContent),
		DocType:      models.PMDocTypeContext,
		SourceType:   models.PMDocSourceRefresh,
		SourceMeta:   meta,
		LastSyncedAt: &now,
		SortOrder:    -1,
	}
	if err := txStore.Create(ctx, pendingDoc); err != nil {
		return fmt.Errorf("create pending refresh doc: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit refresh transaction: %w", err)
	}
	return nil
}
