package auth

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// PreviewWorkerErrorHeader marks errors generated by the worker preview
// control plane itself. The public preview gateway uses it to distinguish
// worker routing/auth failures from ordinary responses returned by previewed
// applications.
const PreviewWorkerErrorHeader = "X-143-Preview-Worker-Error"

// PreviewTokenClaims scopes internal preview control-plane calls.
type PreviewTokenClaims struct {
	OrgID        uuid.UUID  `json:"org_id"`
	TargetNodeID string     `json:"target_node_id"`
	RuntimeID    *uuid.UUID `json:"runtime_id,omitempty"`
	RuntimeEpoch int        `json:"runtime_epoch,omitempty"`
	SessionID    *uuid.UUID `json:"session_id,omitempty"`
	PreviewID    *uuid.UUID `json:"preview_id,omitempty"`
	Action       string     `json:"action"`
	ExpiresAt    time.Time  `json:"exp"`
}

// PreviewTokenKeyring signs preview RPC tokens with the first configured
// secret and validates tokens signed by any configured secret. Secrets are
// intentionally ordered so deploys can keep signing with an old secret while
// first rolling validation support across the fleet, then flip the signer in a
// later deploy.
type PreviewTokenKeyring struct {
	secrets []string
}

// NewPreviewTokenKeyring creates a preview RPC keyring from an ordered secret
// list, dropping blank entries and rejecting an empty effective list.
func NewPreviewTokenKeyring(secrets []string) (PreviewTokenKeyring, error) {
	normalized := make([]string, 0, len(secrets))
	for _, secret := range secrets {
		secret = strings.TrimSpace(secret)
		if secret == "" {
			continue
		}
		normalized = append(normalized, secret)
	}
	if len(normalized) == 0 {
		return PreviewTokenKeyring{}, fmt.Errorf("preview token keyring requires at least one secret")
	}
	return PreviewTokenKeyring{secrets: normalized}, nil
}

// Configured reports whether the keyring has at least one effective secret.
func (k PreviewTokenKeyring) Configured() bool {
	return len(k.secrets) > 0
}

// Generate creates a signed preview token with the first configured secret.
func (k PreviewTokenKeyring) Generate(claims PreviewTokenClaims) (string, error) {
	if len(k.secrets) == 0 {
		return "", fmt.Errorf("preview token keyring requires at least one secret")
	}
	return GeneratePreviewToken(k.secrets[0], claims)
}

// Validate verifies and decodes a token signed by any configured secret.
func (k PreviewTokenKeyring) Validate(token string) (*PreviewTokenClaims, error) {
	if len(k.secrets) == 0 {
		return nil, fmt.Errorf("preview token keyring requires at least one secret")
	}
	var firstErr error
	for _, secret := range k.secrets {
		claims, err := ValidatePreviewToken(secret, token)
		if err == nil {
			return claims, nil
		}
		if firstErr == nil || !strings.Contains(err.Error(), "invalid signature") {
			firstErr = err
		}
	}
	return nil, fmt.Errorf("preview token is not valid for any configured secret: %w", firstErr)
}

// GeneratePreviewToken creates a short-lived HMAC-signed token for internal
// preview RPC between app nodes and workers.
func GeneratePreviewToken(secret string, claims PreviewTokenClaims) (string, error) {
	payload, err := json.Marshal(claims)
	if err != nil {
		return "", fmt.Errorf("marshal claims: %w", err)
	}
	mac := hmac.New(sha256.New, []byte(secret))
	if _, err := mac.Write(payload); err != nil {
		return "", fmt.Errorf("compute HMAC: %w", err)
	}
	sig := mac.Sum(nil)
	return base64.RawURLEncoding.EncodeToString(payload) + "." + base64.RawURLEncoding.EncodeToString(sig), nil
}

// ValidatePreviewToken verifies and decodes an internal preview token.
func ValidatePreviewToken(secret, token string) (*PreviewTokenClaims, error) {
	dotIdx := strings.LastIndexByte(token, '.')
	if dotIdx < 0 {
		return nil, fmt.Errorf("invalid token format")
	}
	payloadB64 := token[:dotIdx]
	sigB64 := token[dotIdx+1:]

	payload, err := base64.RawURLEncoding.DecodeString(payloadB64)
	if err != nil {
		return nil, fmt.Errorf("decode payload: %w", err)
	}
	sig, err := base64.RawURLEncoding.DecodeString(sigB64)
	if err != nil {
		return nil, fmt.Errorf("decode signature: %w", err)
	}

	mac := hmac.New(sha256.New, []byte(secret))
	if _, err := mac.Write(payload); err != nil {
		return nil, fmt.Errorf("compute HMAC: %w", err)
	}
	if !hmac.Equal(sig, mac.Sum(nil)) {
		return nil, fmt.Errorf("invalid signature")
	}

	var claims PreviewTokenClaims
	if err := json.Unmarshal(payload, &claims); err != nil {
		return nil, fmt.Errorf("decode claims: %w", err)
	}
	if time.Now().After(claims.ExpiresAt) {
		return nil, fmt.Errorf("token expired")
	}
	return &claims, nil
}
