package handlers

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/rs/zerolog"

	"github.com/assembledhq/143/internal/auth"
	"github.com/assembledhq/143/internal/db"
	"github.com/assembledhq/143/internal/models"
	"github.com/assembledhq/143/internal/services/publicationintent"
)

// InternalPullRequestHandler handles PR creation requests from sandbox agents
// via internal API tokens.
type InternalPullRequestHandler struct {
	sessionStore     *db.SessionStore
	pullRequestStore *db.PullRequestStore
	changesetStore   *db.SessionChangesetStore
	jobStore         *db.JobStore
	signingSecret    string
	logger           zerolog.Logger
	coordinator      publicationintent.PublicationIntentCoordinator
	threadStore      *db.SessionThreadStore
	audit            *db.AuditEmitter
}

func (h *InternalPullRequestHandler) SetAuditEmitter(audit *db.AuditEmitter) {
	h.audit = audit
}

func (h *InternalPullRequestHandler) SetThreadStore(store *db.SessionThreadStore) {
	h.threadStore = store
}

// SetPublicationIntentCoordinator takes no enable flag: the coordinator is the
// permanent contract boundary for this handler, and execution kill switches are
// resolved inside it.
func (h *InternalPullRequestHandler) SetPublicationIntentCoordinator(
	coordinator publicationintent.PublicationIntentCoordinator,
) {
	h.coordinator = coordinator
}

func (h *InternalPullRequestHandler) SetChangesetStore(store *db.SessionChangesetStore) {
	h.changesetStore = store
}

func NewInternalPullRequestHandler(
	sessionStore *db.SessionStore,
	pullRequestStore *db.PullRequestStore,
	jobStore *db.JobStore,
	signingSecret string,
	logger zerolog.Logger,
) *InternalPullRequestHandler {
	return &InternalPullRequestHandler{
		sessionStore:     sessionStore,
		pullRequestStore: pullRequestStore,
		jobStore:         jobStore,
		signingSecret:    signingSecret,
		logger:           logger,
	}
}

type internalCreatePullRequestRequest struct {
	SessionID   string `json:"session_id,omitempty"`
	Draft       *bool  `json:"draft,omitempty"`
	AuthorMode  string `json:"author_mode,omitempty"`
	TriggerKind string `json:"trigger_kind,omitempty"`
}

type internalCreatePullRequestResponse struct {
	Status         string  `json:"status"`
	SessionID      string  `json:"session_id"`
	PublicationID  *string `json:"publication_id,omitempty"`
	ReviewLoopID   *string `json:"review_loop_id,omitempty"`
	PullRequestURL *string `json:"pull_request_url,omitempty"`
	Reason         *string `json:"reason,omitempty"`
}

// Create handles POST /api/v1/internal/sessions/{sessionID}/pr and the
// current-session POST /api/v1/internal/session/pr route. The latter derives
// session identity exclusively from the signed internal token.
func (h *InternalPullRequestHandler) Create(w http.ResponseWriter, r *http.Request) {
	tokenStr := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
	if tokenStr == "" {
		writeError(w, r, http.StatusUnauthorized, "UNAUTHORIZED", "missing authorization token")
		return
	}
	claims, err := auth.ValidateInternalToken(h.signingSecret, tokenStr)
	if err != nil {
		writeError(w, r, http.StatusUnauthorized, "UNAUTHORIZED", "invalid token", err)
		return
	}
	if claims.SessionOrigin == string(models.SessionOriginAutomationGoalImprovement) {
		writeError(w, r, http.StatusForbidden, "TOOL_NOT_AVAILABLE", "pull request creation is not available to automation goal improvement sessions")
		return
	}

	var sessionID uuid.UUID
	if rawSessionID := strings.TrimSpace(chi.URLParam(r, "sessionID")); rawSessionID != "" {
		sessionID, err = uuid.Parse(rawSessionID)
		if err != nil {
			writeError(w, r, http.StatusBadRequest, "INVALID_ID", "invalid session ID")
			return
		}
	} else if claims.SessionID != nil {
		sessionID = *claims.SessionID
	} else {
		writeError(w, r, http.StatusForbidden, "SESSION_MISMATCH", "token is not authorized for a session")
		return
	}

	var req internalCreatePullRequestRequest
	if r.Body != nil && r.ContentLength != 0 {
		if err := json.NewDecoder(io.LimitReader(r.Body, 1<<20)).Decode(&req); err != nil && !errors.Is(err, io.EOF) {
			writeError(w, r, http.StatusBadRequest, "INVALID_BODY", "invalid request body", err)
			return
		}
	}
	if req.SessionID != "" && req.SessionID != sessionID.String() {
		writeError(w, r, http.StatusBadRequest, "SESSION_MISMATCH", "session_id must match the token-scoped session ID")
		return
	}
	switch req.AuthorMode {
	case "", "auto", "app", "user":
	default:
		writeError(w, r, http.StatusBadRequest, "INVALID_AUTHOR_MODE", "author_mode must be auto, app, or user")
		return
	}
	switch req.TriggerKind {
	case "", string(models.SessionPublicationTriggerAgentReady), string(models.SessionPublicationTriggerExplicitAction):
	default:
		writeError(w, r, http.StatusBadRequest, "INVALID_TRIGGER_KIND", "trigger_kind must be agent_ready or explicit_action")
		return
	}

	// Require a session-scoped token (generated by GenerateSessionToken) so that
	// a sandbox agent cannot queue PRs for sessions other than its own.
	if claims.SessionID == nil || *claims.SessionID != sessionID {
		writeError(w, r, http.StatusForbidden, "SESSION_MISMATCH", "token is not authorized for this session")
		return
	}
	if claims.ThreadID != nil {
		// Fail closed: this is the guard that stops a read-only or review
		// thread from publishing, so a missing store must deny rather than
		// silently skip it.
		if h.threadStore == nil {
			writeError(w, r, http.StatusForbidden, "TOOL_NOT_AVAILABLE", "pull request creation cannot be authorized for this thread")
			return
		}
		thread, threadErr := h.threadStore.GetByID(r.Context(), claims.OrgID, *claims.ThreadID)
		if threadErr != nil {
			writeError(w, r, http.StatusForbidden, "TOOL_NOT_AVAILABLE", "pull request creation is not available to this thread", threadErr)
			return
		}
		if thread.SessionID != sessionID ||
			thread.FilesystemMode == models.ThreadFilesystemModeReadOnly ||
			thread.ExecutionMode == models.ThreadExecutionModeReview {
			writeError(w, r, http.StatusForbidden, "TOOL_NOT_AVAILABLE", "pull request creation is not available to read-only or review threads")
			return
		}
	}

	session, err := h.sessionStore.GetByID(r.Context(), claims.OrgID, sessionID)
	if err != nil {
		writeError(w, r, http.StatusNotFound, "NOT_FOUND", "session not found")
		return
	}
	if session.RepositoryID == nil || *session.RepositoryID != claims.RepoID {
		writeError(w, r, http.StatusForbidden, "REPO_MISMATCH", "token is not authorized for this session repository")
		return
	}
	// The coordinator is now the permanent contract boundary. Execution kill
	// switches are handled inside it and return a typed 202 result; falling back
	// to the legacy queue here would revive retired 409/500 responses and could
	// publish during an emergency stop.
	h.createWithCoordinator(w, r, claims.OrgID, sessionID, req)
}

func (h *InternalPullRequestHandler) createWithCoordinator(
	w http.ResponseWriter,
	r *http.Request,
	orgID, sessionID uuid.UUID,
	req internalCreatePullRequestRequest,
) {
	if h.coordinator == nil {
		writeError(w, r, http.StatusInternalServerError, "PUBLICATION_INTENT_FAILED", "publication coordinator is unavailable")
		return
	}
	triggerKind := models.SessionPublicationTriggerAgentReady
	if req.TriggerKind != "" {
		triggerKind = models.SessionPublicationTriggerKind(req.TriggerKind)
	}
	result, err := h.coordinator.RequestPullRequest(r.Context(), orgID, sessionID, publicationintent.RequestPullRequest{
		Draft: req.Draft, AuthorMode: req.AuthorMode,
		// This endpoint is only reachable with a sandbox-scoped internal
		// token, so the channel is the agent tool regardless of whether the
		// agent is relaying an explicit user instruction via trigger_kind.
		Source:      models.SessionPublicationSourceAgentTool,
		TriggerKind: triggerKind,
	})
	if err != nil {
		var intentErr *publicationintent.Error
		if errors.As(err, &intentErr) {
			switch intentErr.Code {
			case publicationintent.ErrorSessionNotEligible:
				writeError(w, r, http.StatusConflict, string(intentErr.Code), "session is not eligible for publication", err)
			case publicationintent.ErrorWorkspaceNotReady:
				writeError(w, r, http.StatusConflict, string(intentErr.Code), "workspace is not ready for publication", err)
			default:
				writeError(w, r, http.StatusInternalServerError, "PUBLICATION_INTENT_FAILED", "failed to record publication intent", err)
			}
			return
		}
		writeError(w, r, http.StatusInternalServerError, "PUBLICATION_INTENT_FAILED", "failed to record publication intent", err)
		return
	}
	if result == nil {
		writeError(w, r, http.StatusInternalServerError, "PUBLICATION_INTENT_FAILED", "publication coordinator returned no result")
		return
	}
	response := internalCreatePullRequestResponse{
		Status: string(result.Status), SessionID: result.SessionID.String(),
		PullRequestURL: result.PullRequestURL, Reason: result.Reason,
	}
	if result.PublicationID != nil {
		value := result.PublicationID.String()
		response.PublicationID = &value
	}
	if result.ReviewLoopID != nil {
		value := result.ReviewLoopID.String()
		response.ReviewLoopID = &value
	}
	if h.audit != nil {
		resourceID := sessionID.String()
		details, marshalErr := agentPublicationAuditDetails(result, triggerKind)
		if marshalErr != nil {
			h.logger.Warn().Err(marshalErr).Str("session_id", sessionID.String()).Msg("failed to encode agent publication audit details")
		} else {
			h.audit.EmitAgentAction(r.Context(), db.AgentActionParams{
				OrgID: orgID, AgentRunID: sessionID.String(),
				Action:       models.AuditActionSessionPRRequested,
				ResourceType: models.AuditResourceSession, ResourceID: &resourceID,
				Details: details, SessionID: &sessionID,
			})
		}
	}
	writeJSON(w, http.StatusAccepted, response)
}

// agentPublicationAuditDetails records the trigger the caller actually asked
// for. An explicit user request routed through the agent endpoint must not be
// filed in the audit log as agent-initiated readiness.
func agentPublicationAuditDetails(
	result *publicationintent.PublicationIntentResult,
	triggerKind models.SessionPublicationTriggerKind,
) (json.RawMessage, error) {
	return json.Marshal(map[string]any{
		"status":          result.Status,
		"publication_id":  result.PublicationID,
		"trigger_kind":    triggerKind,
		"review_bypassed": result.ReviewBypassed,
	})
}
