package handlers

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog"

	"github.com/assembledhq/143/internal/auth"
	"github.com/assembledhq/143/internal/db"
	"github.com/assembledhq/143/internal/models"
)

// InternalPullRequestHandler handles PR creation requests from sandbox agents
// via internal API tokens.
type InternalPullRequestHandler struct {
	sessionStore     *db.SessionStore
	pullRequestStore *db.PullRequestStore
	changesetStore   *db.SessionChangesetStore
	jobStore         *db.JobStore
	signingSecret    string
	logger           zerolog.Logger
}

func (h *InternalPullRequestHandler) SetChangesetStore(store *db.SessionChangesetStore) {
	h.changesetStore = store
}

func NewInternalPullRequestHandler(
	sessionStore *db.SessionStore,
	pullRequestStore *db.PullRequestStore,
	jobStore *db.JobStore,
	signingSecret string,
	logger zerolog.Logger,
) *InternalPullRequestHandler {
	return &InternalPullRequestHandler{
		sessionStore:     sessionStore,
		pullRequestStore: pullRequestStore,
		jobStore:         jobStore,
		signingSecret:    signingSecret,
		logger:           logger,
	}
}

type internalCreatePullRequestRequest struct {
	SessionID  string `json:"session_id,omitempty"`
	Draft      *bool  `json:"draft,omitempty"`
	AuthorMode string `json:"author_mode,omitempty"`
}

type internalCreatePullRequestResponse struct {
	Status    string `json:"status"`
	SessionID string `json:"session_id"`
}

// Create handles POST /api/v1/internal/sessions/{sessionID}/pr.
func (h *InternalPullRequestHandler) Create(w http.ResponseWriter, r *http.Request) {
	tokenStr := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
	if tokenStr == "" {
		writeError(w, r, http.StatusUnauthorized, "UNAUTHORIZED", "missing authorization token")
		return
	}
	claims, err := auth.ValidateInternalToken(h.signingSecret, tokenStr)
	if err != nil {
		writeError(w, r, http.StatusUnauthorized, "UNAUTHORIZED", "invalid token", err)
		return
	}
	if claims.SessionOrigin == string(models.SessionOriginAutomationGoalImprovement) {
		writeError(w, r, http.StatusForbidden, "TOOL_NOT_AVAILABLE", "pull request creation is not available to automation goal improvement sessions")
		return
	}

	sessionID, err := uuid.Parse(chi.URLParam(r, "sessionID"))
	if err != nil {
		writeError(w, r, http.StatusBadRequest, "INVALID_ID", "invalid session ID")
		return
	}

	var req internalCreatePullRequestRequest
	if r.Body != nil && r.ContentLength != 0 {
		if err := json.NewDecoder(io.LimitReader(r.Body, 1<<20)).Decode(&req); err != nil && !errors.Is(err, io.EOF) {
			writeError(w, r, http.StatusBadRequest, "INVALID_BODY", "invalid request body", err)
			return
		}
	}
	if req.SessionID != "" && req.SessionID != sessionID.String() {
		writeError(w, r, http.StatusBadRequest, "SESSION_MISMATCH", "session_id must match the URL session ID")
		return
	}
	switch req.AuthorMode {
	case "", "auto", "app", "user":
	default:
		writeError(w, r, http.StatusBadRequest, "INVALID_AUTHOR_MODE", "author_mode must be auto, app, or user")
		return
	}

	// Require a session-scoped token (generated by GenerateSessionToken) so that
	// a sandbox agent cannot queue PRs for sessions other than its own.
	if claims.SessionID == nil || *claims.SessionID != sessionID {
		writeError(w, r, http.StatusForbidden, "SESSION_MISMATCH", "token is not authorized for this session")
		return
	}

	session, err := h.sessionStore.GetByID(r.Context(), claims.OrgID, sessionID)
	if err != nil {
		writeError(w, r, http.StatusNotFound, "NOT_FOUND", "session not found")
		return
	}
	if session.RepositoryID == nil || *session.RepositoryID != claims.RepoID {
		writeError(w, r, http.StatusForbidden, "REPO_MISMATCH", "token is not authorized for this session repository")
		return
	}
	changesetID := sessionID
	if h.changesetStore != nil {
		primary, primaryErr := h.changesetStore.GetPrimary(r.Context(), claims.OrgID, sessionID)
		if primaryErr != nil {
			writeError(w, r, http.StatusInternalServerError, "PRIMARY_CHANGESET_FAILED", "failed to resolve the primary pull request target", primaryErr)
			return
		}
		changesetID = primary.ID
		session.PRCreationState = primary.PRCreationState
		session.PRCreationError = primary.PRCreationError
	}

	switch session.PRCreationState {
	case models.PRCreationStateQueued, models.PRCreationStatePushing:
		writeError(w, r, http.StatusConflict, "PR_IN_FLIGHT", "PR creation already in progress")
		return
	case models.PRCreationStateSucceeded:
		writeError(w, r, http.StatusConflict, "PR_ALREADY_CREATED", "PR creation already completed for this session")
		return
	}

	// Catch cases where PRCreationState is stale but a PR record already exists
	// (e.g. state-sync bug). The job-store dedupe key is the authoritative guard
	// against duplicate jobs; this check produces a clearer 409 error for clients.
	_, prErr := h.pullRequestStore.GetPrimaryBySessionID(r.Context(), claims.OrgID, sessionID)
	if prErr == nil {
		writeError(w, r, http.StatusConflict, "PR_EXISTS", "a pull request already exists for this session")
		return
	}
	if !errors.Is(prErr, pgx.ErrNoRows) {
		writeError(w, r, http.StatusInternalServerError, "INTERNAL_ERROR", "failed to check for existing PR", prErr)
		return
	}

	if h.changesetStore == nil {
		err = h.sessionStore.UpdatePRCreationState(r.Context(), claims.OrgID, sessionID, models.PRCreationStateQueued, "")
		if err != nil {
			writeError(w, r, http.StatusInternalServerError, "PR_STATE_FAILED", "failed to reserve pull request creation", err)
			return
		}
	}

	payload := map[string]any{
		"session_id":   sessionID.String(),
		"changeset_id": changesetID.String(),
		"org_id":       claims.OrgID.String(),
	}
	if req.Draft != nil {
		payload["draft"] = *req.Draft
	}
	if req.AuthorMode != "" && req.AuthorMode != "auto" {
		payload["author_mode"] = req.AuthorMode
	}
	if h.changesetStore != nil {
		_, queued, queueErr := h.jobStore.QueueChangesetPRCreation(r.Context(), claims.OrgID, sessionID, changesetID, "agent", payload, 5)
		if queueErr != nil {
			writeError(w, r, http.StatusInternalServerError, "ENQUEUE_FAILED", "failed to enqueue PR creation job", queueErr)
			return
		}
		if !queued {
			writeError(w, r, http.StatusConflict, "PR_IN_FLIGHT", "PR creation already in progress")
			return
		}
	} else {
		dedupeKey := db.OpenPRDedupeKey(changesetID)
		if _, err := h.jobStore.Enqueue(r.Context(), claims.OrgID, "agent", "open_pr", payload, 5, &dedupeKey); err != nil {
			if stateErr := h.sessionStore.UpdatePRCreationState(r.Context(), claims.OrgID, sessionID, models.PRCreationStateFailed, "Could not queue pull request creation."); stateErr != nil {
				h.logger.Warn().Err(stateErr).Str("session_id", sessionID.String()).Msg("failed to restore PR creation state after enqueue failure")
			}
			writeError(w, r, http.StatusInternalServerError, "ENQUEUE_FAILED", "failed to enqueue PR creation job", err)
			return
		}
	}

	writeJSON(w, http.StatusAccepted, internalCreatePullRequestResponse{Status: "queued", SessionID: sessionID.String()})
}
