package handlers

import (
	"errors"
	"strconv"
	"strings"

	"github.com/assembledhq/143/internal/db"
	"github.com/assembledhq/143/internal/models"
)

const autoGeneratedLabelRetryLimit = 20

func normalizedSubscriptionLabel(label string) string {
	return strings.TrimSpace(label)
}

func generatedSubscriptionLabel(user *models.User, attempt int, maxLen int) string {
	base := inferredSubscriptionLabelBase(user)
	if attempt <= 1 {
		return truncateSubscriptionLabel(base, maxLen)
	}

	suffix := " " + strconv.Itoa(attempt)
	baseLimit := maxLen - len(suffix)
	if baseLimit < 1 {
		baseLimit = 1
	}

	return truncateSubscriptionLabel(base, baseLimit) + suffix
}

func inferredSubscriptionLabelBase(user *models.User) string {
	if user != nil {
		if name := strings.Join(strings.Fields(user.Name), " "); name != "" {
			return name
		}
		if user.GitHubLogin != nil {
			if login := strings.TrimSpace(*user.GitHubLogin); login != "" {
				return login
			}
		}
		if email := strings.TrimSpace(user.Email); email != "" {
			if localPart, _, ok := strings.Cut(email, "@"); ok && strings.TrimSpace(localPart) != "" {
				return strings.TrimSpace(localPart)
			}
			return email
		}
	}

	return "Subscription"
}

func truncateSubscriptionLabel(label string, maxLen int) string {
	label = normalizedSubscriptionLabel(label)
	if len(label) <= maxLen {
		return label
	}
	return strings.TrimSpace(label[:maxLen])
}

func resolveSubscriptionLabel(
	requested string,
	user *models.User,
	maxLen int,
	initiate func(label string) error,
) (string, error) {
	requested = normalizedSubscriptionLabel(requested)
	if requested != "" {
		return requested, initiate(requested)
	}

	var lastErr error
	for attempt := 1; attempt <= autoGeneratedLabelRetryLimit; attempt++ {
		label := generatedSubscriptionLabel(user, attempt, maxLen)
		err := initiate(label)
		if err == nil {
			return label, nil
		}

		var labelErr *db.ErrCredentialLabelTaken
		if !errors.As(err, &labelErr) {
			return "", err
		}
		lastErr = err
	}

	return "", lastErr
}
