apiVersion: 1

contactPoints:
  - orgId: 1
    name: platform-warning
    receivers:
      - uid: platform_warning_webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://alert-slack-relay:8080/warning
          httpMethod: POST
          maxAlerts: 20
  - orgId: 1
    name: platform-critical
    receivers:
      - uid: platform_critical_webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://alert-slack-relay:8080/critical
          httpMethod: POST
          maxAlerts: 20
