package db

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/assembledhq/143/internal/models"
)

// PMDocumentStore manages PM documents using the insert-only versioning pattern
// (same as MemoryStore). Updates deactivate the current row and insert a new
// active row within a transaction. The logical_id links all versions of a
// document together.
type PMDocumentStore struct {
	db TxStarter
}

func NewPMDocumentStore(db TxStarter) *PMDocumentStore {
	return &PMDocumentStore{db: db}
}

// Begin starts a transaction using the underlying DB handle.
func (s *PMDocumentStore) Begin(ctx context.Context) (pgx.Tx, error) {
	return s.db.Begin(ctx)
}

// WithTx returns a new PMDocumentStore that uses the given transaction.
func (s *PMDocumentStore) WithTx(tx pgx.Tx) *PMDocumentStore {
	return &PMDocumentStore{db: tx}
}

const pmDocColumns = `id, org_id, title, content, doc_type, sort_order,
	source_type, source_url, source_id, source_meta, last_synced_at,
	active, logical_id, content_hash,
	created_by, created_at, updated_at`

func scanPMDoc(row pgx.Row) (models.PMDocument, error) {
	var d models.PMDocument
	err := row.Scan(
		&d.ID, &d.OrgID, &d.Title, &d.Content, &d.DocType,
		&d.SortOrder, &d.SourceType, &d.SourceURL, &d.SourceID,
		&d.SourceMeta, &d.LastSyncedAt,
		&d.Active, &d.LogicalID, &d.ContentHash,
		&d.CreatedBy, &d.CreatedAt, &d.UpdatedAt,
	)
	return d, err
}

func scanPMDocs(rows pgx.Rows) ([]models.PMDocument, error) {
	var docs []models.PMDocument
	for rows.Next() {
		var d models.PMDocument
		err := rows.Scan(
			&d.ID, &d.OrgID, &d.Title, &d.Content, &d.DocType,
			&d.SortOrder, &d.SourceType, &d.SourceURL, &d.SourceID,
			&d.SourceMeta, &d.LastSyncedAt,
			&d.Active, &d.LogicalID, &d.ContentHash,
			&d.CreatedBy, &d.CreatedAt, &d.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}
		docs = append(docs, d)
	}
	return docs, rows.Err()
}

// contentHash computes a SHA-256 hex digest of the document content.
func contentHash(content string) string {
	h := sha256.Sum256([]byte(content))
	return hex.EncodeToString(h[:])
}

// Create inserts a new PM document with active=true and a fresh logical_id.
func (s *PMDocumentStore) Create(ctx context.Context, doc *models.PMDocument) error {
	if doc.SourceType == "" {
		doc.SourceType = models.PMDocSourceManual
	}
	doc.ContentHash = contentHash(doc.Content)

	query := `
		INSERT INTO pm_documents (
			org_id, title, content, doc_type, sort_order,
			source_type, source_url, source_id, source_meta, last_synced_at,
			active, content_hash,
			created_by
		) VALUES (
			@org_id, @title, @content, @doc_type, @sort_order,
			@source_type, @source_url, @source_id, @source_meta, @last_synced_at,
			true, @content_hash,
			@created_by
		) RETURNING id, logical_id, created_at, updated_at`

	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"org_id":         doc.OrgID,
		"title":          doc.Title,
		"content":        doc.Content,
		"doc_type":       doc.DocType,
		"sort_order":     doc.SortOrder,
		"source_type":    doc.SourceType,
		"source_url":     doc.SourceURL,
		"source_id":      doc.SourceID,
		"source_meta":    doc.SourceMeta,
		"last_synced_at": doc.LastSyncedAt,
		"content_hash":   doc.ContentHash,
		"created_by":     doc.CreatedBy,
	})
	doc.Active = true
	return row.Scan(&doc.ID, &doc.LogicalID, &doc.CreatedAt, &doc.UpdatedAt)
}

// ListByOrg returns all active documents for an org.
func (s *PMDocumentStore) ListByOrg(ctx context.Context, orgID uuid.UUID) ([]models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND active = true
		ORDER BY sort_order ASC, created_at ASC`, pmDocColumns)

	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"org_id": orgID,
	})
	if err != nil {
		return nil, fmt.Errorf("query pm documents: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

// GetByOrgAndSourceType returns the most recently updated active document
// matching the source type. Used to find the singleton autogenerated context doc.
func (s *PMDocumentStore) GetByOrgAndSourceType(ctx context.Context, orgID uuid.UUID, sourceType string) (models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND source_type = @source_type AND active = true
		ORDER BY updated_at DESC LIMIT 1`, pmDocColumns)
	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"org_id":      orgID,
		"source_type": sourceType,
	})
	return scanPMDoc(row)
}

// ListByOrgAndSourceType returns all active documents matching the source type.
func (s *PMDocumentStore) ListByOrgAndSourceType(ctx context.Context, orgID uuid.UUID, sourceType string) ([]models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND source_type = @source_type AND active = true
		ORDER BY updated_at DESC`, pmDocColumns)
	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"org_id":      orgID,
		"source_type": sourceType,
	})
	if err != nil {
		return nil, fmt.Errorf("query pm documents by source type: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

// ListByOrgExcludeSourceType returns active documents for an org, excluding
// those with the given source type. Capped at limit.
func (s *PMDocumentStore) ListByOrgExcludeSourceType(ctx context.Context, orgID uuid.UUID, excludeSourceType string, limit int) ([]models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND source_type != @exclude_source_type AND active = true
		ORDER BY sort_order ASC, created_at ASC
		LIMIT @limit`, pmDocColumns)
	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"org_id":              orgID,
		"exclude_source_type": excludeSourceType,
		"limit":               limit,
	})
	if err != nil {
		return nil, fmt.Errorf("query pm documents excluding source type: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

// GetByID returns a document by ID (any version, active or not).
// This is needed for version history inspection and pin member lookups.
func (s *PMDocumentStore) GetByID(ctx context.Context, orgID, docID uuid.UUID) (models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents WHERE id = @id AND org_id = @org_id`, pmDocColumns)
	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"id":     docID,
		"org_id": orgID,
	})
	return scanPMDoc(row)
}

// Update replaces the current active version with a new row using the
// insert-only versioning pattern. The old row is deactivated and a new row
// is inserted in a single transaction. If no fields changed, this is a no-op.
//
// The doc parameter is updated in-place with the new row's ID, timestamps,
// and logical_id (carried forward from the previous version).
func (s *PMDocumentStore) Update(ctx context.Context, doc *models.PMDocument) error {
	newHash := contentHash(doc.Content)

	tx, err := s.db.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// 1. Fetch the current active row (with row lock) to check for changes.
	// The handler reads the doc outside this transaction, so we verify the
	// row the handler read is still the active one (guards against concurrent updates).
	current, err := scanPMDoc(tx.QueryRow(ctx,
		fmt.Sprintf(`SELECT %s FROM pm_documents WHERE id = @id AND org_id = @org_id AND active = true FOR UPDATE`, pmDocColumns),
		pgx.NamedArgs{"id": doc.ID, "org_id": doc.OrgID},
	))
	if err != nil {
		return fmt.Errorf("fetch current version (row may have been updated concurrently): %w", err)
	}

	// Skip insert if nothing changed across all mutable fields.
	if newHash == current.ContentHash &&
		doc.Title == current.Title &&
		doc.DocType == current.DocType &&
		doc.SortOrder == current.SortOrder &&
		doc.SourceType == current.SourceType &&
		stringPtrEq(doc.SourceURL, current.SourceURL) &&
		stringPtrEq(doc.SourceID, current.SourceID) &&
		bytes.Equal(doc.SourceMeta, current.SourceMeta) &&
		timePtrEq(doc.LastSyncedAt, current.LastSyncedAt) {
		return tx.Commit(ctx)
	}

	// 2. Deactivate the current active row.
	_, err = tx.Exec(ctx,
		`UPDATE pm_documents SET active = false WHERE id = @id AND org_id = @org_id`,
		pgx.NamedArgs{"id": doc.ID, "org_id": doc.OrgID},
	)
	if err != nil {
		return fmt.Errorf("deactivate current version: %w", err)
	}

	// 3. Insert new active version with the same logical_id.
	row := tx.QueryRow(ctx, fmt.Sprintf(`
		INSERT INTO pm_documents (
			org_id, title, content, doc_type, sort_order,
			source_type, source_url, source_id, source_meta, last_synced_at,
			active, logical_id, content_hash,
			created_by
		) VALUES (
			@org_id, @title, @content, @doc_type, @sort_order,
			@source_type, @source_url, @source_id, @source_meta, @last_synced_at,
			true, @logical_id, @content_hash,
			@created_by
		) RETURNING %s`, pmDocColumns),
		pgx.NamedArgs{
			"org_id":         doc.OrgID,
			"title":          doc.Title,
			"content":        doc.Content,
			"doc_type":       doc.DocType,
			"sort_order":     doc.SortOrder,
			"source_type":    doc.SourceType,
			"source_url":     doc.SourceURL,
			"source_id":      doc.SourceID,
			"source_meta":    doc.SourceMeta,
			"last_synced_at": doc.LastSyncedAt,
			"logical_id":     current.LogicalID,
			"content_hash":   newHash,
			"created_by":     doc.CreatedBy,
		},
	)

	updated, err := scanPMDoc(row)
	if err != nil {
		return fmt.Errorf("insert new version: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit transaction: %w", err)
	}

	// Update the doc in-place with the new row's fields.
	*doc = updated
	return nil
}

// stringPtrEq compares two *string values for equality.
func stringPtrEq(a, b *string) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	return *a == *b
}

// timePtrEq compares two *time.Time values for equality.
func timePtrEq(a, b *time.Time) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	return a.Equal(*b)
}

// Delete soft-deletes a document by setting active=false. The row is preserved
// for version history and pin reference integrity.
func (s *PMDocumentStore) Delete(ctx context.Context, orgID, docID uuid.UUID) error {
	_, err := s.db.Exec(ctx,
		`UPDATE pm_documents SET active = false WHERE id = @id AND org_id = @org_id AND active = true`,
		pgx.NamedArgs{"id": docID, "org_id": orgID},
	)
	return err
}

// DeleteByOrgAndSourceType hard-deletes ephemeral documents (e.g., pending
// refresh drafts) that don't participate in versioning or pinning.
// Only deletes rows that are NOT referenced by any pin member (ON DELETE RESTRICT
// on the FK will reject the delete if a pinned row is accidentally targeted).
//
// IMPORTANT: This method should only be called for ephemeral source types
// (PMDocSourceRefresh). Calling it on versioned source types (manual, notion,
// autogenerated, etc.) will permanently destroy version history.
func (s *PMDocumentStore) DeleteByOrgAndSourceType(ctx context.Context, orgID uuid.UUID, sourceType string) error {
	if sourceType != models.PMDocSourceRefresh {
		return fmt.Errorf("DeleteByOrgAndSourceType is restricted to ephemeral source types; got %q", sourceType)
	}
	_, err := s.db.Exec(ctx,
		`DELETE FROM pm_documents
		 WHERE org_id = @org_id AND source_type = @source_type
		   AND id NOT IN (SELECT document_id FROM pm_document_set_pin_members)`,
		pgx.NamedArgs{"org_id": orgID, "source_type": sourceType},
	)
	return err
}

// GetActiveByLogicalID returns the current active version for a given logical_id.
func (s *PMDocumentStore) GetActiveByLogicalID(ctx context.Context, orgID, logicalID uuid.UUID) (models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents WHERE org_id = @org_id AND logical_id = @logical_id AND active = true`, pmDocColumns)
	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"org_id":     orgID,
		"logical_id": logicalID,
	})
	return scanPMDoc(row)
}

// ListVersions returns all versions of a document (active and inactive),
// ordered newest first. The logical_id is resolved from the provided doc ID.
// Limit caps the number of results (0 defaults to 100).
func (s *PMDocumentStore) ListVersions(ctx context.Context, orgID, docID uuid.UUID, limit int) ([]models.PMDocument, error) {
	if limit <= 0 {
		limit = 100
	}
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND logical_id = (
			SELECT logical_id FROM pm_documents WHERE id = @id AND org_id = @org_id
		)
		ORDER BY created_at DESC
		LIMIT @limit`, pmDocColumns)
	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"org_id": orgID,
		"id":     docID,
		"limit":  limit,
	})
	if err != nil {
		return nil, fmt.Errorf("query pm document versions: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

// Restore creates a new active version with the content from an old version.
// This follows the standard insert-only pattern: deactivate current + insert new.
func (s *PMDocumentStore) Restore(ctx context.Context, orgID, currentDocID, restoreFromID uuid.UUID) (models.PMDocument, error) {
	tx, err := s.db.Begin(ctx)
	if err != nil {
		return models.PMDocument{}, fmt.Errorf("begin transaction: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Fetch the version to restore from.
	oldDoc, err := scanPMDoc(tx.QueryRow(ctx,
		fmt.Sprintf(`SELECT %s FROM pm_documents WHERE id = @id AND org_id = @org_id`, pmDocColumns),
		pgx.NamedArgs{"id": restoreFromID, "org_id": orgID},
	))
	if err != nil {
		return models.PMDocument{}, fmt.Errorf("fetch restore source: %w", err)
	}

	// Deactivate the current active version.
	var logicalID uuid.UUID
	err = tx.QueryRow(ctx,
		`UPDATE pm_documents SET active = false
		 WHERE id = @id AND org_id = @org_id AND active = true
		 RETURNING logical_id`,
		pgx.NamedArgs{"id": currentDocID, "org_id": orgID},
	).Scan(&logicalID)
	if err != nil {
		return models.PMDocument{}, fmt.Errorf("deactivate current version: %w", err)
	}

	// Verify both docs belong to the same logical document.
	if oldDoc.LogicalID != logicalID {
		return models.PMDocument{}, fmt.Errorf("restore source belongs to a different logical document")
	}

	// Insert new active version with old content.
	row := tx.QueryRow(ctx, fmt.Sprintf(`
		INSERT INTO pm_documents (
			org_id, title, content, doc_type, sort_order,
			source_type, source_url, source_id, source_meta, last_synced_at,
			active, logical_id, content_hash,
			created_by
		) VALUES (
			@org_id, @title, @content, @doc_type, @sort_order,
			@source_type, @source_url, @source_id, @source_meta, @last_synced_at,
			true, @logical_id, @content_hash,
			@created_by
		) RETURNING %s`, pmDocColumns),
		pgx.NamedArgs{
			"org_id":         oldDoc.OrgID,
			"title":          oldDoc.Title,
			"content":        oldDoc.Content,
			"doc_type":       oldDoc.DocType,
			"sort_order":     oldDoc.SortOrder,
			"source_type":    oldDoc.SourceType,
			"source_url":     oldDoc.SourceURL,
			"source_id":      oldDoc.SourceID,
			"source_meta":    oldDoc.SourceMeta,
			"last_synced_at": oldDoc.LastSyncedAt,
			"logical_id":     logicalID,
			"content_hash":   contentHash(oldDoc.Content),
			"created_by":     oldDoc.CreatedBy,
		},
	)

	restored, err := scanPMDoc(row)
	if err != nil {
		return models.PMDocument{}, fmt.Errorf("insert restored version: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return models.PMDocument{}, fmt.Errorf("commit transaction: %w", err)
	}

	return restored, nil
}

// --- Document Set Pins ---

// CreateDocumentSetPin captures the current active document row IDs as a pin.
func (s *PMDocumentStore) CreateDocumentSetPin(ctx context.Context, orgID uuid.UUID) (models.PMDocumentSetPin, error) {
	tx, err := s.db.Begin(ctx)
	if err != nil {
		return models.PMDocumentSetPin{}, fmt.Errorf("begin transaction: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Create the pin.
	var pin models.PMDocumentSetPin
	err = tx.QueryRow(ctx,
		`INSERT INTO pm_document_set_pins (org_id) VALUES (@org_id) RETURNING id, org_id, created_at`,
		pgx.NamedArgs{"org_id": orgID},
	).Scan(&pin.ID, &pin.OrgID, &pin.CreatedAt)
	if err != nil {
		return models.PMDocumentSetPin{}, fmt.Errorf("create pin: %w", err)
	}

	// Capture all currently active document IDs as pin members.
	_, err = tx.Exec(ctx,
		`INSERT INTO pm_document_set_pin_members (pin_id, document_id)
		 SELECT @pin_id, id FROM pm_documents WHERE org_id = @org_id AND active = true`,
		pgx.NamedArgs{"pin_id": pin.ID, "org_id": orgID},
	)
	if err != nil {
		return models.PMDocumentSetPin{}, fmt.Errorf("create pin members: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return models.PMDocumentSetPin{}, fmt.Errorf("commit transaction: %w", err)
	}

	return pin, nil
}

// GetDocumentSetPin returns a pin by ID.
func (s *PMDocumentStore) GetDocumentSetPin(ctx context.Context, orgID, pinID uuid.UUID) (models.PMDocumentSetPin, error) {
	var pin models.PMDocumentSetPin
	err := s.db.QueryRow(ctx,
		`SELECT id, org_id, created_at FROM pm_document_set_pins WHERE id = @id AND org_id = @org_id`,
		pgx.NamedArgs{"id": pinID, "org_id": orgID},
	).Scan(&pin.ID, &pin.OrgID, &pin.CreatedAt)
	return pin, err
}

// ListDocumentSetPins returns all pins for an org, newest first.
// Limit caps the number of results (0 defaults to 100).
func (s *PMDocumentStore) ListDocumentSetPins(ctx context.Context, orgID uuid.UUID, limit int) ([]models.PMDocumentSetPin, error) {
	if limit <= 0 {
		limit = 100
	}
	rows, err := s.db.Query(ctx,
		`SELECT id, org_id, created_at FROM pm_document_set_pins WHERE org_id = @org_id ORDER BY created_at DESC LIMIT @limit`,
		pgx.NamedArgs{"org_id": orgID, "limit": limit},
	)
	if err != nil {
		return nil, fmt.Errorf("query document set pins: %w", err)
	}
	defer rows.Close()

	var pins []models.PMDocumentSetPin
	for rows.Next() {
		var p models.PMDocumentSetPin
		if err := rows.Scan(&p.ID, &p.OrgID, &p.CreatedAt); err != nil {
			return nil, err
		}
		pins = append(pins, p)
	}
	return pins, rows.Err()
}

// GetPinMembers returns all document versions that belong to a pin.
func (s *PMDocumentStore) GetPinMembers(ctx context.Context, orgID, pinID uuid.UUID) ([]models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents d
		INNER JOIN pm_document_set_pin_members m ON d.id = m.document_id
		WHERE m.pin_id = @pin_id AND d.org_id = @org_id
		ORDER BY d.sort_order ASC, d.created_at ASC`, pmDocColumnsQualified())
	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"pin_id": pinID,
		"org_id": orgID,
	})
	if err != nil {
		return nil, fmt.Errorf("query pin members: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

// pmDocColumnsQualified returns the column list with "d." table alias prefix.
func pmDocColumnsQualified() string {
	return `d.id, d.org_id, d.title, d.content, d.doc_type, d.sort_order,
	d.source_type, d.source_url, d.source_id, d.source_meta, d.last_synced_at,
	d.active, d.logical_id, d.content_hash,
	d.created_by, d.created_at, d.updated_at`
}
