package db

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/assembledhq/143/internal/models"
)

type PMDocumentStore struct {
	db DBTX
}

func NewPMDocumentStore(db DBTX) *PMDocumentStore {
	return &PMDocumentStore{db: db}
}

// Begin starts a transaction using the underlying DB handle.
func (s *PMDocumentStore) Begin(ctx context.Context) (pgx.Tx, error) {
	txStarter, ok := s.db.(TxStarter)
	if !ok {
		return nil, fmt.Errorf("pm document store db does not support transactions")
	}
	return txStarter.Begin(ctx)
}

// WithTx returns a new PMDocumentStore that uses the given transaction.
func (s *PMDocumentStore) WithTx(tx pgx.Tx) *PMDocumentStore {
	return &PMDocumentStore{db: tx}
}

const pmDocColumns = `id, org_id, title, content, doc_type, sort_order,
	source_type, source_url, source_id, source_meta, last_synced_at,
	created_by, created_at, updated_at`

func scanPMDoc(row pgx.Row) (models.PMDocument, error) {
	var d models.PMDocument
	err := row.Scan(
		&d.ID, &d.OrgID, &d.Title, &d.Content, &d.DocType,
		&d.SortOrder, &d.SourceType, &d.SourceURL, &d.SourceID,
		&d.SourceMeta, &d.LastSyncedAt, &d.CreatedBy, &d.CreatedAt, &d.UpdatedAt,
	)
	return d, err
}

func scanPMDocs(rows pgx.Rows) ([]models.PMDocument, error) {
	var docs []models.PMDocument
	for rows.Next() {
		var d models.PMDocument
		err := rows.Scan(
			&d.ID, &d.OrgID, &d.Title, &d.Content, &d.DocType,
			&d.SortOrder, &d.SourceType, &d.SourceURL, &d.SourceID,
			&d.SourceMeta, &d.LastSyncedAt, &d.CreatedBy, &d.CreatedAt, &d.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}
		docs = append(docs, d)
	}
	return docs, rows.Err()
}

func (s *PMDocumentStore) Create(ctx context.Context, doc *models.PMDocument) error {
	query := `
		INSERT INTO pm_documents (
			org_id, title, content, doc_type, sort_order,
			source_type, source_url, source_id, source_meta, last_synced_at,
			created_by
		) VALUES (
			@org_id, @title, @content, @doc_type, @sort_order,
			@source_type, @source_url, @source_id, @source_meta, @last_synced_at,
			@created_by
		) RETURNING id, created_at, updated_at`

	if doc.SourceType == "" {
		doc.SourceType = models.PMDocSourceManual
	}

	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"org_id":         doc.OrgID,
		"title":          doc.Title,
		"content":        doc.Content,
		"doc_type":       doc.DocType,
		"sort_order":     doc.SortOrder,
		"source_type":    doc.SourceType,
		"source_url":     doc.SourceURL,
		"source_id":      doc.SourceID,
		"source_meta":    doc.SourceMeta,
		"last_synced_at": doc.LastSyncedAt,
		"created_by":     doc.CreatedBy,
	})
	return row.Scan(&doc.ID, &doc.CreatedAt, &doc.UpdatedAt)
}

func (s *PMDocumentStore) ListByOrg(ctx context.Context, orgID uuid.UUID) ([]models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id
		ORDER BY sort_order ASC, created_at ASC`, pmDocColumns)

	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"org_id": orgID,
	})
	if err != nil {
		return nil, fmt.Errorf("query pm documents: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

// GetByOrgAndSourceType returns the most recently updated document matching the
// source type. Used to find the singleton autogenerated context doc for an org.
func (s *PMDocumentStore) GetByOrgAndSourceType(ctx context.Context, orgID uuid.UUID, sourceType string) (models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND source_type = @source_type
		ORDER BY updated_at DESC LIMIT 1`, pmDocColumns)
	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"org_id":      orgID,
		"source_type": sourceType,
	})
	return scanPMDoc(row)
}

// ListByOrgAndSourceType returns all documents matching the source type for an org.
func (s *PMDocumentStore) ListByOrgAndSourceType(ctx context.Context, orgID uuid.UUID, sourceType string) ([]models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND source_type = @source_type
		ORDER BY updated_at DESC`, pmDocColumns)
	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"org_id":      orgID,
		"source_type": sourceType,
	})
	if err != nil {
		return nil, fmt.Errorf("query pm documents by source type: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

// ListByOrgExcludeSourceType returns documents for an org, excluding those with the
// given source type. Results are ordered by sort_order and capped at limit.
func (s *PMDocumentStore) ListByOrgExcludeSourceType(ctx context.Context, orgID uuid.UUID, excludeSourceType string, limit int) ([]models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents
		WHERE org_id = @org_id AND source_type != @exclude_source_type
		ORDER BY sort_order ASC, created_at ASC
		LIMIT @limit`, pmDocColumns)
	rows, err := s.db.Query(ctx, query, pgx.NamedArgs{
		"org_id":              orgID,
		"exclude_source_type": excludeSourceType,
		"limit":               limit,
	})
	if err != nil {
		return nil, fmt.Errorf("query pm documents excluding source type: %w", err)
	}
	defer rows.Close()
	return scanPMDocs(rows)
}

func (s *PMDocumentStore) GetByID(ctx context.Context, orgID, docID uuid.UUID) (models.PMDocument, error) {
	query := fmt.Sprintf(`SELECT %s FROM pm_documents WHERE id = @id AND org_id = @org_id`, pmDocColumns)
	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"id":     docID,
		"org_id": orgID,
	})
	return scanPMDoc(row)
}

func (s *PMDocumentStore) Update(ctx context.Context, doc *models.PMDocument) error {
	query := `UPDATE pm_documents SET
		title = @title, content = @content, doc_type = @doc_type,
		sort_order = @sort_order, source_type = @source_type,
		source_url = @source_url, source_id = @source_id,
		source_meta = @source_meta, last_synced_at = @last_synced_at,
		updated_at = now()
		WHERE id = @id AND org_id = @org_id
		RETURNING updated_at`
	row := s.db.QueryRow(ctx, query, pgx.NamedArgs{
		"id":             doc.ID,
		"org_id":         doc.OrgID,
		"title":          doc.Title,
		"content":        doc.Content,
		"doc_type":       doc.DocType,
		"sort_order":     doc.SortOrder,
		"source_type":    doc.SourceType,
		"source_url":     doc.SourceURL,
		"source_id":      doc.SourceID,
		"source_meta":    doc.SourceMeta,
		"last_synced_at": doc.LastSyncedAt,
	})
	return row.Scan(&doc.UpdatedAt)
}

func (s *PMDocumentStore) Delete(ctx context.Context, orgID, docID uuid.UUID) error {
	_, err := s.db.Exec(ctx,
		`DELETE FROM pm_documents WHERE id = @id AND org_id = @org_id`,
		pgx.NamedArgs{"id": docID, "org_id": orgID},
	)
	return err
}

// DeleteByOrgAndSourceType deletes all documents matching the org and source type
// in a single query, avoiding the need to list+loop.
func (s *PMDocumentStore) DeleteByOrgAndSourceType(ctx context.Context, orgID uuid.UUID, sourceType string) error {
	_, err := s.db.Exec(ctx,
		`DELETE FROM pm_documents WHERE org_id = @org_id AND source_type = @source_type`,
		pgx.NamedArgs{"org_id": orgID, "source_type": sourceType},
	)
	return err
}
